### ISSUE TITLE
Not able to add stream data to redis using Nodejs

### ISSUE THREAD

**Issue by chiragkhanna28** [redis/node-redis#1607]
Hi Team,

I am trying to add data to the redis stream using Nodejs but the data could not be added. I am using below code:

redisClient.sendCommand(`XADD ${streamName} * name test`, [], function (error: any, res: any) {
        console.log(error);
        console.log('a', res);
 });

I am using redis version 3.1. Can you please help me with this?

Regards,
Chirag Khanna

**Comment by leibale** [comment]
The Redis Server version is 3.1 or the client version is 3.1? [cause Redis streams were introduced in 5.0](https://redis.io/topics/streams-intro)..

**Comment by chiragkhanna28** [comment]
Hi @leibale,

The client version is 3.1 and server version is above 6 and we tried above query as well but it doesn't works as well.

Regards,
Chirag Khanna

**Comment by leibale** [comment]
@chiragkhanna28 can you please share the error message?

**Comment by BigShanJohn** [comment]
(node:15972) UnhandledPromiseRejectionWarning: ReplyError: ERR unknown command 'X'
    at parseError (C:\xampp\htdocs\registration-service\node_modules\redis-parser\lib\parser.js:179:12)
    at parseType (C:\xampp\htdocs\registration-service\node_modules\redis-parser\lib\parser.js:302:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15972) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15972) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

when doing this  
```
await client.sendCommand('XADD', [streamName, '*', 'name', 'test'], function(err, reply) {
        console.log(err, reply);
    });
```

**Comment by danialrp** [comment]
receiving same error here.

```
await client.sendCommand('XADD', [streamName, '*', 'name', 'test'], function(err, reply) {
        console.log(err, reply);
    });
```

Error:

```
(node:19769) UnhandledPromiseRejectionWarning: ReplyError: ERR unknown command 'X', with args beginning with: 'A', 'D', 'D', 
    at parseError (/Users/danial/code/wss-rate/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/Users/danial/code/wss-rate/node_modules/redis-parser/lib/parser.js:302:14)
(Use 'node --trace-warnings ...' to show where the warning was created)
(node:19769) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag '--unhandled-rejections=strict' (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19769) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

also similar error with 
```
await redisClient.sendCommand('XREAD', ['BLOCK', 1000, 'STREAMS', 'streamName', '$'], function (err: any, reply: any) {
            console.log(err, reply);
        })
```

Error
```
(node:19740) UnhandledPromiseRejectionWarning: ReplyError: ERR unknown command 'X', with args beginning with: 'R', 'E', 'A', 'D', 
    at parseError (/Users/danial/code/wss-rate/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/Users/danial/code/wss-rate/node_modules/redis-parser/lib/parser.js:302:14)
(Use 'node --trace-warnings ...' to show where the warning was created)
(node:19740) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag '--unhandled-rejections=strict' (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19740) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

in my case the reason of using Raw redis commands in the first place is after i'm adding a stream with "xAdd "

```
await redisClient.xAdd('streamName', '*', "some:key", "test-value").then(function (id) {
            console.log("id:", id);
        });

# id: 1640198099428-0
# id: 1640198101308-0
# id: 1640198102266-0
# id: 1640198102637-0
# id: 1640198103358-0
# id: 1640198104458-0
```

i can't get the stream with "xRead" as it's always returning this error
```
(node:19642) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at encodeCommand (/Users/user/code/project/node_modules/@node-redis/client/dist/lib/commander.js:71:104)
    at encodeCommand.next (<anonymous>)
    at RedisSocket.writeCommand (/Users/user/code/project/node_modules/@node-redis/client/dist/lib/client/socket.js:56:20)
    at Commander._RedisClient_tick (/Users/user/code/project/node_modules/@node-redis/client/dist/lib/client/index.js:421:64)
    at RedisSocket.<anonymous> (/Users/user/code/project/node_modules/@node-redis/client/dist/lib/client/index.js:338:86)
    at RedisSocket.emit (events.js:315:20)
    at RedisSocket._RedisSocket_connect (/Users/user/code/project/node_modules/@node-redis/client/dist/lib/client/socket.js:136:10)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Commander.connect (/Users/user/code/project/node_modules/@node-redis/client/dist/lib/client/index.js:156:9)
(Use 'node --trace-warnings ...' to show where the warning was created)
```

can anyone help plz?!

**Comment by danialrp** [comment]
Ok, the right way to use "XADD" and "XREAD" through the sendCommand is
```
await client.sendCommand(['XADD', 'streamName', '*', 'name', 'test'], function(err, reply) {
        console.log(err, reply);
    });


await redisClient.sendCommand(['XREAD', 'BLOCK', '1000', 'STREAMS', 'streamName', '$'], function (err, reply) {
            console.log(err, reply);
        })
```

**Comment by simonprickett** [comment]
Closing as resolved.
