### ISSUE TITLE
Quit is not allowed on PubSub

### ISSUE THREAD

**Issue by AleksandrSl** [redis/node-redis#1766]
I get this error when I'm trying to `client.quit()` on the PubSub client. [In the redis docs](https://redis.io/topics/pubsub) it's said that QUIT is allowed on PubSub. Am I missing something?

```
FATAL  Cannot send commands in PubSub mode at 2021-12-06 12:21:12
        at RedisCommandsQueue.addCommand (./node_modules/@node-redis/client/dist/lib/client/commands-queue.js:68:35)
        at /home/aleksandrsl/Projects/akeero-logux/node_modules/@node-redis/client/dist/lib/client/index.js:213:87
        at RedisSocket.quit (./node_modules/@node-redis/client/dist/lib/client/socket.js:76:15)
        at Commander.QUIT (./node_modules/@node-redis/client/dist/lib/client/index.js:212:71)
        at file:///home/aleksandrsl/Projects/akeero-logux/vendor/add-scaling.js:12:35
        at file:///home/aleksandrsl/Projects/akeero-logux/node_modules/@logux/server/base-server/index.js:447:45
```

**Environment:**
 - **Node.js Version**: v14.18.1
 - **Redis Server Version**: 6.2.6
 - **Node Redis Version**: 4.0.0
 - **Platform**: Fedora 34

**Comment by AleksandrSl** [comment]
Thanks!
