### ISSUE TITLE
Redis client unexpectedly closes & reconnects every 10 mins for infinite number of times

### ISSUE THREAD

**Issue by saikumar1607** [redis/node-redis#1776]
I'm establishing the redis client to connect to an tls enabled remote redis server. The redis client created using `client.connect()` gets closed with `SocketClosedUnexpectedlyError` and immediately reconnects at every 10th minute.
This happens infinitely.

**CODE**
`connectionUrl` - `rediss://user:password@host:31018/3`
```js
const redis = require('redis');
const client = redis.createClient({
    url: connectionUrl,
    socket: {
        ca: "the-tls-certicate"
    }
});

// Register events handlers for redis
client.on('error', (err) => { console.log('Time', new Date().toLocaleString('sv'), 'Error establishing a redis database connection.', err); });
client.on('end', () => { console.log('Time', new Date().toLocaleString('sv'), 'Redis client disconnected.'); });
client.on('ready', () => { console.log('Time', new Date().toLocaleString('sv'), 'Redis client successfully connected with database'); });

// connect to redisdb using redisClient
(async () => {
    await client.connect();
})();
```

**OUTPUT** (logged the timestamp also to show the proof)
```log
Time 2021-12-09 21:53:57 Redis client successfully connected with database
Time 2021-12-09 22:03:57 Error establishing a redis database connection. SocketClosedUnexpectedlyError: Socket closed unexpectedly
    at TLSSocket.<anonymous> (/node_modules/@node-redis/client/dist/lib/client/socket.js:176:118)
    at Object.onceWrapper (node:events:510:26)
    at TLSSocket.emit (node:events:402:35)
    at node:net:687:12
    at TCP.done (node:_tls_wrap:580:7)
Time 2021-12-09 22:03:59 Redis client successfully connected with database
Time 2021-12-09 22:13:59 Error establishing a redis database connection. SocketClosedUnexpectedlyError: Socket closed unexpectedly
    at TLSSocket.<anonymous> (/node_modules/@node-redis/client/dist/lib/client/socket.js:176:118)
    at Object.onceWrapper (node:events:510:26)
    at TLSSocket.emit (node:events:402:35)
    at node:net:687:12
    at TCP.done (node:_tls_wrap:580:7)
Time 2021-12-09 22:13:59 Redis client successfully connected with database
Time 2021-12-09 22:14:59 Error establishing a redis database connection. SocketClosedUnexpectedlyError: Socket closed unexpectedly
    at TLSSocket.<anonymous> (/node_modules/@node-redis/client/dist/lib/client/socket.js:176:118)
    at Object.onceWrapper (node:events:510:26)
    at TLSSocket.emit (node:events:402:35)
    at node:net:687:12
    at TCP.done (node:_tls_wrap:580:7)
Time 2021-12-09 22:14:59 Redis client successfully connected with database
Time 2021-12-09 22:15:59 Error establishing a redis database connection. SocketClosedUnexpectedlyError: Socket closed unexpectedly
    at TLSSocket.<anonymous> (/node_modules/@node-redis/client/dist/lib/client/socket.js:176:118)
    at Object.onceWrapper (node:events:510:26)
    at TLSSocket.emit (node:events:402:35)
    at node:net:687:12
    at TCP.done (node:_tls_wrap:580:7)
Time 2021-12-09 22:15:59 Redis client successfully connected with database
.
.
.
so on...
```

**Environment:**
 - **Node.js Version**: 14.18.2
 - **Redis Server Version**: 6.0.16
 - **Node Redis Version**: 4.0.0
 - **Platform**: Mac OS 11.6

**Comment by leibale** [comment]
`SocketClosedUnexpectedlyError` means that the socket was closed by the server side, does your redis-server seats behind a load-balancer or something like that?

**Comment by saikumar1607** [comment]
Yes @leibale you are correct. I confirmed that the 10 min unexpected closer event is coming from our redis-server. Nothing related to redis package 4.0.0
Thank you for the quick reply
