### ISSUE TITLE
redis.xRead() always returning undefined

### ISSUE THREAD

**Issue by danialrp** [redis/node-redis#1797]
Added a stream with "xAdd"
```
await redisClient.xAdd('streamName', '*', "some:key", "test-value").then(function (id) {
            console.log("id:", id);
        });

# id: 1640198099428-0
# id: 1640198101308-0
# id: 1640198102266-0
# id: 1640198102637-0
# id: 1640198103358-0
# id: 1640198104458-0
```
then trying to read it with "xRead"
```
await redisClient.xRead('BLOCK', '1000', 'STREAMS', 'streamName', '$', async (err, stream) => {
            if (err) return console.error('Error reading from stream:', err);
            console.log('Stream:', stream);
        })
```
no matter what, it's always returning this error
```
(node:19642) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at encodeCommand (/Users/user/code/project/node_modules/@node-redis/client/dist/lib/commander.js:71:104)
    at encodeCommand.next (<anonymous>)
    at RedisSocket.writeCommand (/Users/user/code/project/node_modules/@node-redis/client/dist/lib/client/socket.js:56:20)
    at Commander._RedisClient_tick (/Users/user/code/project/node_modules/@node-redis/client/dist/lib/client/index.js:421:64)
    at RedisSocket.<anonymous> (/Users/user/code/project/node_modules/@node-redis/client/dist/lib/client/index.js:338:86)
    at RedisSocket.emit (events.js:315:20)
    at RedisSocket._RedisSocket_connect (/Users/user/code/project/node_modules/@node-redis/client/dist/lib/client/socket.js:136:10)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Commander.connect (/Users/user/code/project/node_modules/@node-redis/client/dist/lib/client/index.js:156:9)
(Use 'node --trace-warnings ...' to show where the warning was created)
```
any thoughts ?

**Comment by leibale** [comment]
```javascript
const id = await client.xAdd('streamName', '*', { name: 'test' });

const messages = await client.xRead(
  commandOptions({ isolated: true }), // https://github.com/redis/node-redis/blob/master/docs/isolated-execution.md
  { key: 'streamName', id: '$' },
  { BLOCK: 1000 }
);

// using .sendCommand
await client.sendCommand(['XADD', 'streamName', '*', 'name', 'test']);
await client.sendCommand(['XREAD', 'BLOCK', '1000', 'STREAMS', 'streamName', '$'])

```

**Comment by simonprickett** [comment]
There's also now a stream reading example with a regular consumer here: https://github.com/redis/node-redis/blob/master/examples/stream-consumer.js

And as part of a consumer group here: https://github.com/redis/node-redis/blob/master/examples/stream-consumer-group.js
