### ISSUE TITLE
redis 4: ERR_INVALID_ARG_TYPE The "chunk" argument must be of type string

### ISSUE THREAD

**Issue by cesco69** [redis/node-redis#1818]
Error

```shell
TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer. Received type function ([Function])

at validChunk (_stream_writable.js:281:10)
at Socket.Writable.write (_stream_writable.js:316:21)
at RedisSocket.writeCommand (\node_modules\@node-redis\client\dist\lib\client\socket.js:57:130)
at Commander._RedisClient_tick (\node_modules\@node-redis\client\dist\lib\client\index.js:421:64)
at Commander._RedisClient_sendCommand (\node_modules\@node-redis\client\dist\lib\client\index.js:402:82)
at Commander.sendCommand (\node_modules\@node-redis\client\dist\lib\client\index.js:356:93)
at Commander.<computed>.<computed> (\node_modules\@node-redis\client\dist\lib\client\index.js:390:27)
at new RedisAdapter (\node_modules\@socket.io\redis-adapter\dist\index.js:75:28)
at new <anonymous> (\node_modules\@socket.io\redis-adapter\dist\index.js:45:16)
at Namespace._initAdapter (\node_modules\socket.io\dist\namespace.js:40:24)
```

**package.json**

```json
"dependencies": {
    "@socket.io/redis-adapter": "^7.1.0",
    "express": "^4.17.2",
    "express-socket.io-session": "^1.3.5",
    "redis": "^4.0.1",
    "socket.io": "^4.4.1",
    "socket.io-client": "^4.4.1",
}
```

Example of implementation

```ts
import { createAdapter } from '@socket.io/redis-adapter';
import * as redis from 'redis';
import * as SocketIO from 'socket.io';

// ...

const socketServer = new SocketIO.Server( ... );

const pubClient = redis.createClient({
    url: `redis://localhost:6379`,
    legacyMode: true,
});
const subClient = pubClient.duplicate();

await pubClient.connect();
await subClient.connect();

socketServer.adapter(createAdapter(pubClient, subClient));
```

**Comment by smrutikant** [comment]
@cesco69 Hey There! I too have faced a similar kind of error today, saying 
"TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received type number (1)".

Later I realised that one of the arguments that i am passing while calling one of the client's method(in my case it was sendCommand method) need to be explicitly passed as string. So i converted that argument to string using toString() method and called the same method which worked fine for me. 

Coming to your code block,  however i do not see any such type of methods that are getting called which arguments need to be string. Are these errors are getting triggered from some other set of scripts which are interlinked to the script you have mentioned here?

**Comment by leibale** [comment]
`@socket.io/redis-adapter` added support for `redis@^4.0.0` in [`7.1.0`](https://github.com/socketio/socket.io-redis-adapter/releases/tag/7.1.0). If this bug still exists, please open it in [this repository](https://github.com/socketio/socket.io-redis-adapter).
