### ISSUE TITLE
TypeError: listeners is not iterable

### ISSUE THREAD

**Issue by Ceneka** [redis/node-redis#1997]
I'm getting this and i'm unable to track it to a certain portion of my code. How can I debug it better? None of those file are actual part of my code. Thanks!

```
TypeError: listeners is not iterable
    at Function._RedisCommandsQueue_emitPubSubMessage (/usr/src/app/node_modules/redis/dist/lib/commands-queue.js:203:28)
    at JavascriptRedisParser.returnReply (/usr/src/app/node_modules/redis/dist/lib/commands-queue.js:52:127)
    at JavascriptRedisParser.execute (/usr/src/app/node_modules/redis-parser/lib/parser.js:544:14)
    at RedisCommandsQueue.parseResponse (/usr/src/app/node_modules/redis/dist/lib/commands-queue.js:179:71)
    at RedisSocket.<anonymous> (/usr/src/app/node_modules/redis/dist/lib/client.js:321:83)
    at RedisSocket.emit (node:events:390:28)
    at Socket.<anonymous> (/usr/src/app/node_modules/redis/dist/lib/socket.js:177:44)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)
```

**Environment:**
 - **Node.js Version**:  node 16 last
 - **Redis Server Version**: 6
 - **Node Redis Version**:  ^4.0.0-rc.2
 - **Platform**: Docker Alpine

**Comment by leibale** [comment]
Hi @Ceneka, why are you still using the RC version? Wanna try to reproduce it with version 4.0.3?

**Comment by Ceneka** [comment]
@leibale Hi!, I figured out that was a new version before I opened the issue, so I'm testing right now. In the last 24 hours the issue didn't appear again
