### ISSUE TITLE
cannot connect with tls

### ISSUE THREAD

**Issue by MayasHaddad** [redis/node-redis#2030]
I followed both [examples](https://github.com/redis/node-redis/blob/master/docs/client-configuration.md#tls) with the credentials generated [here](https://docs.redis.com/latest/rc/security/database-security/tls-ssl/) (tried with both "enforce client authentication" options)

I am able to successfully using [redis-cli](https://docs.redis.com/latest/rc/security/database-security/tls-ssl/)

But when I try to login using node-redis:

```ts
createClient({
      url,
      socket: {
        tls: true,
        cert: readFileSync(
          'redislabs_credentials/redislabs_user.crt',
        ),
        ca: readFileSync(
          'redislabs_credentials/redislabs_ca.pem',
        ),
      },
    });
```

I get:

```
ReplyError: ERR unencrypted connection is prohibited
    at parseError (/Users/mayas/bold/core/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/Users/mayas/bold/core/node_modules/redis-parser/lib/parser.js:302:14)
```

 **Environment:**
 - **Node.js Version**: 16.3
 - **Redis Server Version**: 6.2.3
 - **Node Redis Version**: 4.0.4
 - **Platform**: Mac OS 11.4

**Comment by gkorland** [comment]
@MayasHaddad did you set the url prefix to `rediss` ?

**Comment by jaschaio** [comment]
@MayasHaddad I think you need to combine the `redislabs_user.crt` and `redislabs_user_private.key` into a single file and use that for the `socket.cert` option.
