### ISSUE TITLE
SocketClosedUnexpectedlyError: Socket closed unexpectedly

### ISSUE THREAD

**Issue by wyvasi** [redis/node-redis#2032]
Good day!
The socket connection closes unexpectedly and doesn't reconnect, my older version of node-redis(2.8.0) was reconnecting fine and still does.
After reconnect it doesn't print **ready** anymore. 
We are using AWS ElastiCache.
I can only reproduce this on production env. 
We have a package that wraps node-redis and is used in all our apps, so I don't think is related to version difference.
I tried to comment out next code and it doesn't close the connection at all (from @socket.io/redis-adapter).
```
this.subClient.pSubscribe(this.channel + "*", (msg, channel) => {
    this.onmessage(null, channel, msg);
}, true);
````

```
Redis connected
Redis ready!
Redis connected
Redis ready!
fetch error Error: timeout reached while waiting for fetchSockets response
    at Timeout._onTimeout (C:\work\test-socket\node_modules\@socket.io\redis-adapter\dist\index.js:615:28)
    at listOnTimeout (node:internal/timers:568:17)
    at processTimers (node:internal/timers:510:7)
List with sockets connected to hello room: 0
List with sockets connected to hello room: 5
SocketClosedUnexpectedlyError: Socket closed unexpectedly
    at Socket.<anonymous> (C:\work\test-socket\node_modules\@node-redis\client\dist\lib\client\socket.js:195:118)
    at Object.onceWrapper (node:events:510:26)
    at Socket.emit (node:events:390:28)
    at TCP.<anonymous> (node:net:687:12)
Redis reconnecting
Redis connected
ParserError: Protocol error, got "n" as reply type byte
    at handleError (C:\work\test-socket\node_modules\redis-parser\lib\parser.js:190:15)
    at parseType (C:\work\test-socket\node_modules\redis-parser\lib\parser.js:304:14) {
  offset: 304,
  buffer: '....'
```
Here is where I catch the parser error:
client/socket.ts
```
if (this.#initiator) {
            try {
                await this.#initiator();
            } catch (err) {
```
List with buffers and offsets:
```
[{
        offset: 405,
        buffer: '{"type":"Buffer","data":[42,52,13,10,36,56,13,10,112,109,101,115,115,97,103,101,13,10,36,49,50,13,10,105,110,116,101,114,97,99,116,35,47,35,42,13,10,36,54,52,13,10,105,110,116,101,114,97,99,116,35,47,35,104,105,115,82,111,111,109,114,104,122,78,49,49,74,80,98,111,113,107,54,120,78,103,80,52,100,121,71,102,106,84,120,75,86,115,121,98,88,106,107,108,56,56,45,50,66,119,76,65,112,73,99,35,13,10,36,49,53,53,13,10,147,166,119,65,102,98,82,66,131,164,116,121,112,101,2,164,100,97,116,97,146,173,110,111,116,105,102,105,99,97,116,105,111,110,115,130,165,99,111,117,110,116,205,5,184,164,116,121,112,101,181,110,111,116,105,102,105,99,97,116,105,111,110,115,95,99,111,117,110,116,101,114,163,110,115,112,161,47,131,165,114,111,111,109,115,145,217,52,104,105,115,82,111,111,109,114,104,122,78,49,49,74,80,98,111,113,107,54,120,78,103,80,52,100,121,71,102,106,84,120,75,86,115,121,98,88,106,107,108,56,56,45,50,66,119,76,65,112,73,99,166,101,120,99,101,112,116,144,165,102,108,97,103,115,128,13,10,42,52,13,10,36,56,13,10,112,109,101,115,115,97,103,101,13,10,36,49,50,13,10,105,110,116,101,114,97,99,116,35,47,35,42,13,10,36,54,52,13,10,105,110,116,101,114,97,99,116,35,47,35,104,105,115,82,111,111,109,100,76,57,116,118,98,120,51,84,118,52,114,56,87,114,109,56,83,78,89,50,71,53,110,98,80,114,97,112,85,70,116,71,50,107,74,76,116,90,45,50,66,57,105,85,35,13,10,36,49,53,51,13,10,147,166,119,65,102,98,82,66,131,164,116,121,112,101,2,164,100,97,116,97,146,173,110,111,116,105,102,105,99,97,116,105,111,110,115,130,165,99,111,117,110,116,110,164,116,121,112,101,181,110,111,116,105,102,105,99,97,116,105,111,110,115,95,99,111,117,110,116,101,114,163,110,115,112,161,47,131,165,114,111,111,109,115,145,217,52,104,105,115,82,111,111,109,100,76,57,116,118,98,120,51,84,118,52,114,56,87,114,109,56,83,78,89,50,71,53,110,98,80,114,97,112,85,70,116,71,50,107,74,76,116,90,45,50,66,57,105,85,166,101,120,99,101,112,116,144,165,102,108,97,103,115,128,13,10,42,52,13,10,36,56,13,10,112,109,101,115,115,97,103,101,13,10,36,49,50,13,10,105,110,116,101,114,97,99,116,35,47,35,42,13,10,36,54,50,13,10,105,110,116,101,114,97,99,116,35,47,35,104,105,115,82,111,111,109,120,89,112,113,90,54,101,111,89,48,107,120,90,105,81,86,113,97,111,89,90,99,69,119,121,72,50,100,70,122,78,115,108,52,82,50,114,122,111,109,85,113,107,35,13,10,36,49,53,49,13,10,147,166,119,65,102,98,82,66,131,164,116,121,112,101,2,164,100,97,116,97,146,173,110,111,116,105,102,105,99,97,116,105,111,110,115,130,165,99,111,117,110,116,113,164,116,121,112,101,181,110,111,116,105,102,105,99,97,116,105,111,110,115,95,99,111,117,110,116,101,114,163,110,115,112,161,47,131,165,114,111,111,109,115,145,217,50,104,105,115,82,111,111,109,120,89,112,113,90,54,101,111,89,48,107,120,90,105,81,86,113,97,111,89,90,99,69,119,121,72,50,100,70,122,78,115,108,52,82,50,114,122,111,109,85,113,107,166,101,120,99,101,112,116,144,165,102,108,97,103,115,128,13,10,42,52,13,10,36,56,13,10,112,109,101,115,115,97,103,101,13,10,36,49,50,13,10,105,110,116,101,114,97,99,116,35,47,35,42,13,10,36,54,50,13,10,105,110,116,101,114,97,99,116,35,47,35,104,105,115,82,111,111,109,53,111,74,87,66,49,70,85,50,108,109,86,73,54,55,70,106,68,99,83,103,71,118,121,68,48,76,66,83,90,67,83,97,67,113,103,97,69,115,86,119,120,85,35,13,10,36,49,53,50,13,10,147,166,119,65,102,98,82,66,131,164,116,121,112,101,2,164,100,97,116,97,146,173,110,111,116,105,102,105,99,97,116,105,111,110,115,130,165,99,111,117,110,116,204,203,164,116,121,112,101,181,110,111,116,105,102,105,99,97,116,105,111,110,115,95,99,111,117,110,116,101,114,163,110,115,112,161,47,131,165,114,111,111,109,115,145,217,50,104,105,115,82,111,111,109,53,111,74,87,66,49,70,85,50,108,109,86,73,54,55,70,106,68,99,83,103,71,118,121,68,48,76,66,83,90,67,83,97,67,113,103,97,69,115,86,119,120,85,166,101,120,99,101,112,116,144,165,102,108,97,103,115,128,13,10,42,52,13,10,36,56,13,10,112,109,101,115,115,97,103,101,13,10,36,49,50,13,10,105,110,116,101,114,97,99,116,35,47,35,42,13,10,36,54,52,13,10,105,110,116,101,114,97,99,116,35,47,35,104,105,115,82,111,111,109,53,85,74,71,49,53,87,110,116,103,79,88,115,116,106,115,49,45,50,66,82,66,76,106,72,102,82,68,65,109,115,122,112,98,114,82,86,82,69,102,73,50,105,53,85,35,13,10,36,49,53,52,13,10,147,166,119,65,102,98,82,66,131,164,116,121,112,101,2,164,100,97,116,97,146,173,110,111,116,105,102,105,99,97,116,105,111,110,115,130,165,99,111,117,110,116,204,155,164,116,121,112,101,181,110,111,116,105,102,105,99,97,116,105,111,110,115,95,99,111,117,110,116,101,114,163,110,115,112,161,47,131,165,114,111,111,109,115,145,217,52,104,105,115,82,111,111,109,53,85,74,71,49,53,87,110,116,103,79,88,115,116,106,115,49,45,50,66,82,66,76,106,72,102,82,68,65,109,115,122,112,98,114,82,86,82,69,102,73,50,105,53,85,166,101,120,99,101,112,116,144,165,102,108,97,103,115,128,13,10]}'
    },
    {
        offset: 136,
        buffer: '{"type":"Buffer","data":[42,51,13,10,36,57,13,10,115,117,98,115,99,114,105,98,101,13,10,36,49,57,13,10,105,110,116,101,114,97,99,116,45,114,101,113,117,101,115,116,35,47,35,13,10,58,49,13,10,42,51,13,10,36,57,13,10,115,117,98,115,99,114,105,98,101,13,10,36,50,48,13,10,105,110,116,101,114,97,99,116,45,114,101,115,112,111,110,115,101,35,47,35,13,10,58,50,13,10,42,51,13,10,36,57,13,10,115,117,98,115,99,114,105,98,101,13,10,36,50,55,13,10,105,110,116,101,114,97,99,116,45,114,101,115,112,111,110,115,101,35,47,35,88,115,52,75,106,79,35,13,10,58,51,13,10,42,51,13,10,36,57,13,10,115,117,98,115,99,114,105,98,101,13,10,36,50,52,13,10,105,110,116,101,114,97,99,116,45,114,101,113,117,101,115,116,35,47,97,100,109,105,110,35,13,10,58,52,13,10,42,51,13,10,36,57,13,10,115,117,98,115,99,114,105,98,101,13,10,36,50,53,13,10,105,110,116,101,114,97,99,116,45,114,101,115,112,111,110,115,101,35,47,97,100,109,105,110,35,13,10,58,53,13,10,42,51,13,10,36,57,13,10,115,117,98,115,99,114,105,98,101,13,10,36,51,50,13,10,105,110,116,101,114,97,99,116,45,114,101,115,112,111,110,115,101,35,47,97,100,109,105,110,35,104,65,112,66,90,76,35,13,10,58,54,13,10,42,51,13,10,36,49,48,13,10,112,115,117,98,115,99,114,105,98,101,13,10,36,49,50,13,10,105,110,116,101,114,97,99,116,35,47,35,42,13,10,58,55,13,10,42,51,13,10,36,49,48,13,10,112,115,117,98,115,99,114,105,98,101,13,10,36,49,55,13,10,105,110,116,101,114,97,99,116,35,47,97,100,109,105,110,35,42,13,10,58,56,13,10]}'
    },
    {
        offset: 12,
        buffer: '{"type":"Buffer","data":[42,52,13,10,36,56,13,10,112,109,101,115,115,97,103,101,13,10,36,49,50,13,10,105,110,116,101,114,97,99,116,35,47,35,42,13,10,36,54,56,13,10,105,110,116,101,114,97,99,116,35,47,35,104,105,115,82,111,111,109,90,71,86,107,121,121,84,115,98,77,84,45,50,66,111,76,53,69,104,82,106,69,121,81,78,116,48,100,69,57,99,66,52,45,50,70,54,67,90,76,113,81,113,45,50,66,117,81,119,35,13,10,36,49,53,56,13,10,147,166,119,65,102,98,82,66,131,164,116,121,112,101,2,164,100,97,116,97,146,173,110,111,116,105,102,105,99,97,116,105,111,110,115,130,165,99,111,117,110,116,204,131,164,116,121,112,101,181,110,111,116,105,102,105,99,97,116,105,111,110,115,95,99,111,117,110,116,101,114,163,110,115,112,161,47,131,165,114,111,111,109,115,145,217,56,104,105,115,82,111,111,109,90,71,86,107,121,121,84,115,98,77,84,45,50,66,111,76,53,69,104,82,106,69,121,81,78,116,48,100,69,57,99,66,52,45,50,70,54,67,90,76,113,81,113,45,50,66,117,81,119,166,101,120,99,101,112,116,144,165,102,108,97,103,115,128,13,10]}'
    },
    {
        offset: 88,
        buffer: '{"type":"Buffer","data":[42,52,13,10,36,56,13,10,112,109,101,115,115,97,103,101,13,10,36,49,50,13,10,105,110,116,101,114,97,99,116,35,47,35,42,13,10,36,54,56,13,10,105,110,116,101,114,97,99,116,35,47,35,104,105,115,82,111,111,109,89,111,97,115,90,54,72,53,80,45,50,66,71,45,50,66,80,45,50,66,80,49,90,106,82,87,74,87,87,83,54,113,72,74,50,86,120,80,77,68,78,51,117,81,101,120,75,87,81,35,13,10,36,49,53,56,13,10,147,166,104,55,52,78,66,121,131,164,116,121,112,101,2,164,100,97,116,97,146,173,110,111,116,105,102,105,99,97,116,105,111,110,115,130,165,99,111,117,110,116,204,194,164,116,121,112,101,181,110,111,116,105,102,105,99,97,116,105,111,110,115,95,99,111,117,110,116,101,114,163,110,115,112,161,47,131,165,114,111,111,109,115,145,217,56,104,105,115,82,111,111,109,89,111,97,115,90,54,72,53,80,45,50,66,71,45,50,66,80,45,50,66,80,49,90,106,82,87,74,87,87,83,54,113,72,74,50,86,120,80,77,68,78,51,117,81,101,120,75,87,81,166,101,120,99,101,112,116,144,165,102,108,97,103,115,128,13,10]}'
    }]
```

Code for creating the client
```
const Redis = require('redis');
Redis.debug_mode = true;

const getClient = async (url) => {

    const client = Redis.createClient({
        socket: {
            host: url
            port: 6379,
        }
    });
    client.on('error', (err) => {
        console.error(err);
    });
    client.on('connect', () => {
        console.log('Redis connected');
    });
    client.on('reconnecting', () => {
        console.log('Redis reconnecting');
    });
    client.on('ready', () => {
        console.log('Redis ready!');
    });

    await client.connect();
    return client;
};

module.exports = {
    getClient,
};


```

**Environment:**
 - **Node.js Version**:  v17.3.1
 - **Redis Server Version**: 6.2
 - **Node Redis Version**: 4.0.3
 - **Platform**: Ubuntu and Windows 10

**Comment by wyvasi** [comment]
After disconnect/reconnect it stops receiving messages. With the older version of node-redis it was reconnecting without any problems. I added some code to print the parser error.
```
const { getClient } = require('./libs/redis');
const { redisUrl, key } = require('./config');

const start = async () => {
    const client = await getClient(redisUrl);
    client.pSubscribe(key + '#/#*', (msg, channel) => {
        onmessage();
    }, true);
    client.pSubscribe( key + '#/admin#*', (msg, channel) => {
        onmessage();
    }, true);
};

start().catch(err => console.log(err));

let x = 0;
const onmessage = (channel, msg) => {
    x++;
};

setInterval(() => {console.log(`Got ${x} messages!`)}, 5000);

```

```
const Redis = require('redis');

const onRedisError = (err) => {console.error(err)};
const onRedisConnect = () => {console.log('Redis connected')};
const onRedisReconnecting = () => {console.log('Redis reconnecting')};
const onRedisReady = () => {console.log('Redis ready!')};

const getClient = async (url) => {
    const client = Redis.createClient({
        socket: {
            host: url.replace('redis://', '').replace(':6379', ''),
            port: 6379,
        }
    });
    client.on('error', onRedisError);
    client.on('connect', onRedisConnect);
    client.on('reconnecting', onRedisReconnecting);
    client.on('ready', onRedisReady);

    await client.connect();
    return client;
};

module.exports = {
    getClient,
};

```

Output:
```
Redis connected
Redis ready!
Got 261 messages!
Got 1751 messages!
Got 3573 messages!
Got 5616 messages!
Got 8532 messages!
Got 9348 messages!
Got 9623 messages!
Got 10069 messages!
Got 11630 messages!
Got 11828 messages!
Got 12844 messages!
Got 14737 messages!
SocketClosedUnexpectedlyError: Socket closed unexpectedly
    at Socket.<anonymous> (C:\work\test-socket\node_modules\@node-redis\client\dist\lib\client\socket.js:196:118)
    at Object.onceWrapper (node:events:510:26)
    at Socket.emit (node:events:390:28)
    at TCP.<anonymous> (node:net:687:12)
Redis reconnecting
Redis connected
ParserError: Protocol error, got "e" as reply type byte
    at handleError (C:\work\test-socket\node_modules\redis-parser\lib\parser.js:190:15)
    at parseType (C:\work\test-socket\node_modules\redis-parser\lib\parser.js:304:14) {
  offset: 358,
  buffer: '{"type":"Buffer","data":[42,52,13,10,36,56,13,10,112,109,101,11.......
}
Got 16116 messages!
Got 16116 messages!
Got 16116 messages!
Got 16116 messages!
Got 16116 messages!
Got 16116 messages!
Got 16116 messages!
Got 16116 messages!
Got 16116 messages!
```

**Comment by rpong** [comment]
We are currently stuck with v3 for months now because this issue seems to be still unresolved with v4.

**Comment by erajanraja24** [comment]
@rpong Could you please update the tentative ETA for this issue as it is a blocker for v4?

**Comment by rpong** [comment]
> @rpong Could you please update the tentative ETA for this issue as it is a blocker for v4?

Hi @erajanraja24, @leibale would be the best person to ask, I am not part of the team..

**Comment by leibale** [comment]
This code does not reproduce the issue (I'm running `docker restart` while the code is running)
```javascript
import { createClient } from '@node-redis/client';

async function client() {
    const client = createClient();

    client.on('error', err => console.error('client error', err));
    client.on('connect', () => console.log('client is connect'));
    client.on('reconnecting', () => console.log('client is reconnecting'));
    client.on('ready', () => console.log('client is ready'));

    await client.connect();

    return client;
}

const [subscriber, publisher] = await Promise.all([
    client(),
    client()
]);

let counter = 0;
subscriber.pSubscribe('*', () => counter++, true);
setInterval(() => console.log(`Got ${counter} messages!`), 1000);

setInterval(async () => {
    try {
        await publisher.publish('channel', 'message');
    } catch (err) {
        console.error('publish error', err);
    }
}, 5);
```

```
client error Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1146:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 6379
}
client is reconnecting
client is reconnecting
client is connect
client is connect
client is ready
Got 484 messages!
Got 484 messages!
client is ready
Got 677 messages!
Got 868 messages!
```

**Comment by rpong** [comment]
just tested 4.1.0, and reconnect still doesn't work like it used to in V3.

**Comment by leibale** [comment]
https://github.com/redis/node-redis/issues/1985#issuecomment-1116865925

**Comment by rpong** [comment]
> ```js
>     client.on('error', err => console.error('client error', err));
>     client.on('connect', () => console.log('client is connect'));
>     client.on('reconnecting', () => console.log('client is reconnecting'));
>     client.on('ready', () => console.log('client is ready'));
> ```

Thanks @leibale , i have discovered that this IS working if we do following before the "await client.connect();"

```
client.on('error', err => console.log('client error', err));
client.on('connect', () => console.log('client is connect'));
client.on('reconnecting', () => console.log('client is reconnecting'));
client.on('ready', () => console.log('client is ready'));
```

but without the above, it doesn't reconnect like v3 does. We can upgrade now and just pass debug info for the above, but would like to confirm if this is the intended behavior.

**Comment by leibale** [comment]
`client.on('error')` was required in v3 as well (see https://nodejs.org/api/events.html#error-events)

**Comment by rpong** [comment]
> https://nodejs.org/api/events.html#error-events

In our case, we did not have this at all for v3 but reconnecting was working.

Thank you for the info, we can finally upgrade to v4 after many months.

**Comment by cheesecakeassassin** [comment]
I can confirm that the code above that leibale provided fixes the issue! My issue in particular was that I had deployed my app using Redis to Heroku and upon the socket closing unexpectedly, the Heroku-deployed app would crash until I redeployed it. The problem was driving me nuts and this was the only solution on the web that helped.

**Comment by KunalBurangi** [comment]
@leibale , The issue persists in v4 and yes it does reconnect. but is there any particular reason why is it crashing unexpectedly? 
yes we do have load-balancer and proxies like gateway and Nginx

**Comment by derikb** [comment]
I should add I _was_ getting the ready event in dev testing if I just stopped/started redis. It seems to still be a problem for whatever is happening when the socket closes unexpectedly. (In my case via an AWS Elasticache.

**Comment by ryanmeador** [comment]
I believe I'm experiencing this issue on 4.2.0.  I set my event listeners like this:
```typescript
  client.on('error', err => log.error(`Redis error: ${err}`));
  client.on('reconnecting', params => log.info(`Redis reconnecting, attempt ${params.attempt}`));
  client.on('connect', () => log.info('Redis connected'));
  client.on('ready', () => log.info('Redis ready'));
  client.on('end', () => log.info('Redis connection closed'));
```

When it starts up, I see this in the log:
```
INFO redis: Redis connected
INFO redis: Redis ready
```

After a while, it disconnects.  I'm using Heroku's Redis server, which seems to drop connections after a few minutes, I think in an attempt to clean up stale connections.  Before upgrading from 3.x.x, it would reconnect seamlessly.  Now, all I see is this:

```
ERROR redis: Redis error: Error: Socket closed unexpectedly
```
No reconnect, no ready.  I have to restart my Node process to get it working again.  Can you offer any advice?

**Comment by ryanmeador** [comment]
I think I have discovered the cause of my problem.  I was expecting a `params` object to be passed to my reconnect event handler, but this was apparently removed in v4.  Since my handler was now accessing an undefined property, it was throwing an error at runtime.  This error was silently swallowed, but still prevented the reconnection.  Could you please log errors of this nature, and still continue with the reconnect?  No doubt it will help others in the future who face a similar problem.

**Comment by leibale** [comment]
@ryanmeador can you please open a new issue with reproduction?

**Comment by CaCaBlocker** [comment]
Hi, I got this same issue on heroku and I changed to the latest version(4.2.0), and still got the same issue after some minutes.

![image](https://user-images.githubusercontent.com/87882515/183118358-db6cb2b9-2ad7-4943-b632-99ceed838dcd.png)

**Comment by leibale** [comment]
@CaCaBlocker there are so many things that can cause this error (and most of them has nothing to-do with the client it-self), for example there is some kind of a proxy/load balancer in between the redis-server and the node server that causes this problem, or that the event loop was blocked for too long, and some more options that I can't remember right now..

Without a reproduction I won't be able to debug and hopefully solve it.

**Comment by bmiller59** [comment]
For anyone still having this issue, I can confirm that adding this code resolved the issue for us.
```
    client.on('error', err => console.error('client error', err));
    client.on('connect', () => console.log('client is connect'));
    client.on('reconnecting', () => console.log('client is reconnecting'));
    client.on('ready', () => console.log('client is ready'));
```
But I also had to make sure that I had removed any other client error listeners that were re-throwing the error (or any other error).

**Comment by polearnik** [comment]
also  you need to add listeners to publishers and subscribers

**Comment by MartinSchere** [comment]
I cannot confirm that this issue is fixed:
```ts
    const client = createClient({
      url: configService.get('SCROLLS_TX_REDIS_URL'),
      socket: {
        reconnectStrategy: (retries) => {
          console.log('RETRYING');
          return Math.min(retries * 100, 1000);
        },
        connectTimeout: configService.get('REDIS_CONNECT_TIMEOUT'),
      },
    });
    await client.connect();
```

Randomly disconnects and never logs `RETRYING`.

**Comment by leibale** [comment]
@flashtheman where is your redis server hosted? what version of node-redis are you using?

**Comment by jorenvandeweyer** [comment]
@leibale 

Seeing the same on a managed redis db on digitalocean after upgrading.

Redis 6
node-redis: 4.5.1

**Comment by Nekidev** [comment]
Same issue here. Just installed, worked for a while and suddenly started conecting, disconncting and reconnecting without being able to do nothing.

**Comment by leibale** [comment]
@Nekidev @ahmedalmulki when this error occurs it's probably because:
1. some proxies close idle connections, see [this comment](https://github.com/redis/node-redis/issues/2032#issuecomment-1343974026)
2. if the number of clients is bigger than `CONFIG GET maxclients`, the server will close some clients. you can check that using `INFO CLIENTS`.

**Comment by derikb** [comment]
fwiw my issue was not that the connection was closing, it was that the reconnection wasn't finishing. That seems like what a lot of people are reporting, contra this issue title, the original issue was "After reconnect it doesn't print ready anymore." which is what I was seeing. I don't think we can avoid connections closing for various reasons some time, but recovering from those closed connections is what still has me on the old version.

**Comment by leibale** [comment]
@derikb I've tried to stop and start the server process and to use the `CLIENT KILL` command, in both cases the client recovers. If you can help me reproduce the issue it'll be awsome :)

**Comment by derikb** [comment]
@leibale yeah that's the issue I had (see further up the thread https://github.com/redis/node-redis/issues/2032#issuecomment-1128975739 ). Manually stopping redis didn't trigger it. I couldn't figure out how to trigger it in dev, but it happened a few times in production (with AWS ElasticCache is was nigh impossible to figure out _what_ had caused it). It was always that the ready event just wouldn't get triggered across any of the connections... just  the unexpected close error, the reconnecting, the connect... then nothing.

**Comment by leibale** [comment]
@derikb your comment is before [this comment](https://github.com/redis/node-redis/issues/2032#issuecomment-1206821861), so maybe the problem you faced is already fixed?

**Comment by derikb** [comment]
@leibale I don't think so. I wasn't expecting or using any args on the reconnect handler. I was just logging that the event happened. And that log entry was getting logged.

**Comment by leibale** [comment]
@derikb maybe the changes in #2295 fixed it? if you have a staging server that you can test it on it'll be very helpful :)

**Comment by derikb** [comment]
@leibale any ideas on how I get redis to unexpectedly close that isn't just a stop/start? I tried that and it would not recreate the original issue. I assume cause the stop process closes connections in an orderly way

**Comment by fabioselau077** [comment]
> @leibale
> 
> Seeing the same on a managed redis db on digitalocean after upgrading.
> 
> Redis 6 node-redis: 4.5.1

same, using redis db on digitalocean
How to fixe?

**Comment by leibale** [comment]
@fabioselau077 https://www.digitalocean.com/community/questions/idle-redis-connection-reconnects-every-five-minutes
try to enable `pingInterval` and set it to less than 5 minutes (`4 * 60 * 1000`  should do it)

**Comment by ilhmyz** [comment]
@fabioselau077 
using redis db on digitalocean try to set TLS to true
see https://github.com/redis/node-redis/blob/master/docs/client-configuration.md#TLS

**Comment by HenonoaH** [comment]
> **Hi, I got this same issue on heroku and I changed to the latest version(4.2.0), and still got the same issue after some minutes.**
> 
> This is my code.
> 
> ```
> import { createClient } from 'redis';
> import config from 'config'
> 
> const redisUrl = config.get<string>("redisUrl");
> 
> const redisClient = createClient({
>   url: redisUrl,
> });
> 
> const connectRedis = async () => {
>   try {
>     await redisClient.connect();
>     console.log('Redis client connect successfully');
>     redisClient.set('try', 'Hello Welcome to Express with TypeORM');
>   } catch (error) {
>     console.log(error);
>     setTimeout(connectRedis, 5000);
>   }
> };
> 
> connectRedis();
> 
> export default redisClient;
> ```
> 
> Is there a solution for this? Or maybe I rewrite the code?

@CaCaBlocker I having the same issue from Redis hosted in Heroku. Did you get any solution or workaround for this?

**Comment by polearnik** [comment]
@HenonoaH  try to add listeners to all available events like ready reconnect error etc.

**Comment by leonardovenoso** [comment]
Changing to redis-server version 6 on Ubuntu and Nodejs Redis 4.6.6 it works fine.
NestJS example:

import { Module } from '@nestjs/common';
import { createClient } from 'redis';
import { ConfigService } from '@nestjs/config';

@Module({
  providers: [
    {
      inject: [ConfigService],
      provide: 'REDIS_CLIENT',
      useFactory: async (configService: ConfigService) => {
        const redisCli = createClient({
          url: `redis://${configService.get('REDIS_USER')}:${configService.get('REDIS_PASSWORD')}@${configService.get('REDIS_HOST')}:${configService.get('REDIS_PORT')}`,
        });

        redisCli.on('connect', () => {
          console.log('Connected to Redis');
        });
        
        redisCli.on('error', (err) => {
          console.log(err.message);
        });
        
        redisCli.on('ready', () => {
          console.log('Redis is ready');
        });
        
        redisCli.on('reconnecting', () => {
          console.log('client is reconnecting')
        });

        redisCli.on('end', () => {
          console.log('Redis connection ended');
        })
        
        process.on('SIGINT', () => {
          redisCli.quit();
        });

        return redisCli;
      }
    }
  ],
  exports: ['REDIS_CLIENT'],
})
export class RedisCliModule {}

**Comment by hieuhuynhh** [comment]
> @fabioselau077 @jorenvandeweyer https://www.digitalocean.com/community/questions/idle-redis-connection-reconnects-every-five-minutes try to set `pingInterval` to a value lower than 5 minutes (`4 * 60 * 1000` should do it)

Hi @leibale, I'm using ioredis and i don't see pingInterval option. How can i solve it with ioredis? Thanks.

**Comment by leibale** [comment]
@hieuhuynhh a simple `setInterval` should fix it:
```javascript
const timer = setInterval(async () => {
  try {
    await client.ping();
  } catch (err) {
    console.error('Ping Interval Error', err);
  }
}, 1000 * 60 * 4);

// make sure to `clearInterval` when you close the client
clearInterval(timer);
client.disconnect();
```

**Comment by niksy** [comment]
Although [documentation](https://github.com/redis/node-redis#basic-example) mentions setting handler for error event, it is not clear that this is actually needed to have this issue fixed. There weren’t any errors of this kind in v3.

Is there a reason why this happens in v4? Can we somehow check for that error inside error handler besides it’s message content? There isn’t any error code for that, and `instanceof` check is not inituitive since errors modules is not exposed publicly.

**Comment by leibale** [comment]
@niksy https://github.com/redis/node-redis#events

":warning: You MUST listen to error events. If a client doesn't have at least one error listener registered and an error occurs, that error will be thrown and the Node.js process will exit. See the [EventEmitter docs](https://nodejs.org/api/events.html#events_error_events) for more details."

**Comment by leibale** [comment]
@niksy https://github.com/redis/node-redis/issues/1993#issuecomment-1558774230

**Comment by ishaarawy** [comment]
changing from socket connection to url solved the issue on local machine connecting to docker container

**Comment by djdabs** [comment]
not sure if related but I'm getting similar errors. All event listeners are configured. Application is a nestjs server talking to memorystore redis in GCP (idle connections are not automatically closed).

client initially connects -> socket gets closed -> client tries reconnecting -> uncaught exception occurs for socket closing

```
 async connectToRedis(): Promise<void>{
    try{
      const pubClient = createClient({
          socket: {
                host: process.env.REDIS_HOST,
                port: Number(process.env.REDIS_PORT)
         },
      });
  
      const subClient = pubClient.duplicate();
  
      pubClient.on('error', (error) => {
        console.error('pubClient redis error:', error);
      });
      pubClient.on('connect', () => console.log('pubClient redis is connected'));
      pubClient.on('reconnecting', () => console.log('pubClient redis is reconnecting'));
      pubClient.on('ready', () => console.log('pubClient redis is ready'));
      
      subClient.on('error', (error) => {
        console.error('subClient redis error:', error);
      });
      subClient.on('connect', () => console.log('subClient redis is connected'));
      subClient.on('reconnecting', () => console.log('subClient redis is reconnecting'));
      subClient.on('ready', () => console.log('subClient redis is ready'));
  
      await pubClient.connect()
      await subClient.connect()
  
      // await redisClient.connect();
     
      this.adapterConstructor = createAdapter(pubClient, subClient);
    } catch(err){
      console.log(err)
    }
    
  }
  ```
![CleanShot 2023-06-02 at 14 50 03](https://github.com/redis/node-redis/assets/87738563/ddc44764-6046-4418-85b6-674d30be1785)

**Comment by niksy** [comment]
@djdabs try this: https://github.com/redis/node-redis/issues/2443#issuecomment-1573393354

**Comment by djdabs** [comment]
> @djdabs try this: [#2443 (comment)](https://github.com/redis/node-redis/issues/2443#issuecomment-1573393354)

Still getting a triggerUncaugthException on reconnect but I'm now getting a different error. 

```
Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:930:11)
    at Socket._write (node:net:942:8)
    at doWrite (node:internal/streams/writable:411:12)
    at clearBuffer (node:internal/streams/writable:572:7)
    at Writable.uncork (node:internal/streams/writable:351:7)
    at Immediate._onImmediate (/usr/src/app/node_modules/@redis/client/dist/lib/client/socket.js:84:69)
    at process.processImmediate (node:internal/timers:476:21) {
```

![CleanShot 2023-06-05 at 11 37 28](https://github.com/redis/node-redis/assets/87738563/d6bfb4c8-7e11-4ab8-91cd-4ce7da83e1a0)

**Comment by djdabs** [comment]
resolved my issue.. after switching to ioredis the error message got more specific and I was able to track down the underlying problem (redis required TLS). Disabled TLS on memorystore and it was able to work now. 

`redis error: ParserError: Protocol error, got "\u0015" as reply type byte. Please report this`

**Comment by stefanodecillis** [comment]
Are there any updates on this issue? I'm currently facing the same problem while using a Redis instance served by Digital Ocean. TLS is in place and the job is listening on "error" - each time the issue occurs, I reset the connection. I don't know if it is the best solution but it kind of works even if it throws the error every five minutes.

In the previous comments, there is a suggestion that pings the server. Do you think that is the best way to handle it at the moment? Or should we wait the patch?

**Comment by jorenvandeweyer** [comment]
@stefanodecillis You can just use `pingInterval` since #2524 is fixed in version `redis@4.6.8`

**Comment by shobhitbehl98** [comment]
Getting the same error at v4.6.12
`const redis = require('redis');
require('dotenv').config();
const client = redis.createClient({
  url: process.env.KV_URL
});
(async () => {
  await client.connect();
})();
client.on('connect', () => {
  console.log('Connected to Redis');
});

client.on('error', (err) => {
  console.error(`Redis Error: ${err}`);
});

client.on('reconnecting', () => console.log('client is reconnecting'));
client.on('ready', () => console.log('client is ready'));

module.exports = client;`

This is the error im gettting

**Comment by jake-chambers** [comment]
We are experiencing the same issue. We're listening error events explicitly...our connection logic is below:
```
export const createRedisClient = (options: RedisClientOptions) => {
    const client = createClient(options);
    client.on('error', async error => {
        console.error(`Redis client error : ${error}`);
        Sentry.captureException(error); // Capture the error with Sentry

        if (
            error.code === 'ECONNRESET' ||
            error.code === 'EPIPE' ||
            error.code === 'ECONNREFUSED'
        ) {
            // Disconnect before attempting to reconnect
            await client.disconnect();

            client.connect().catch(err => {
                console.error(`Failed to reconnect redis client: ${err}`);
                Sentry.captureException(err); // Capture the reconnection error with Sentry
            });
        }
    });
    client.connect().catch(err => {
        console.error(`Failed to connect redis client: ${err}`);
        Sentry.captureException(err); // Capture the reconnection error with Sentry
    });
    return client;
};
```

**Comment by arpit-absyadav** [comment]
The error message indicates that Redis is running in protected mode due to enabled protected mode and the absence of a password for the default user. In this mode, connections are only accepted from the loopback interface. To enable connections from external computers, you can choose one of the following solutions:

Disable protected mode by executing the command: 'CONFIG SET protected-mode no'.
