### ISSUE TITLE
clientSetName crashes

### ISSUE THREAD

**Issue by volnyansky** [redis/node-redis#2070]
`
 await redis.clientSetName("CONNECTION NAME");
`
When I try to execute clientSetName method, I get the following error:
`
ReplyError: ERR unknown command `C`, with args beginning with: `L`, `I`, `E`, `N`, `T`, 

    at parseError (/.../node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/.../node_modules/redis-parser/lib/parser.js:302:14)
`
**Environment:**
 - **Node.js Version**: 16.13.1
 - **Redis Server Version**:  6.2.6
 - **Node Redis Version**:  4.0.6
 - **Platform**:  Mac OS 12.3.1

**Comment by volnyansky** [comment]
@leibale 
You are right . I get error only if name contains space.
