### ISSUE TITLE
4.1.0 not supported on Node 12

### ISSUE THREAD

**Issue by bizob2828** [redis/node-redis#2117]
This may be expected based on this [PR](https://github.com/redis/node-redis/pull/2111/files) but I don't see a changelog entry for 4.1.0 yet.  

## Steps to reproduce
 * `npm i redis@4.1.0` on node 12.
 * `require('redis')

## Expected Result
module works as expected

## Actual Result
crash because library is using optional chaining.

```
node_modules/redis/dist/index.js:42
            ...options?.modules
                       ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/revans/code/pull-requests/node-newrelic/test/versioned/redis/test.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

**Environment:**
 - **Node.js Version**:  12.22.12
 - **Redis Server Version**:  N/A
 - **Node Redis Version**: 4.1.0
 - **Platform**: N/A

**Comment by bizob2828** [comment]
I'm actually going to close this. I forgot LTS support was dropped last week.

**Comment by rithuacharya** [comment]
Hey @bizob2828 , is the optional chaining removed, my strapi application using docker fails because of this change. Using node v14 in docker doesn't work either. Please update on this issue. Thanks.

**Comment by Q-dimi** [comment]
same issue

**Comment by bhartendu27** [comment]
Upgrading my node version to current stable version fixed it for me. (my strapi version: 3.6.8)

```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```

**Comment by rithuacharya** [comment]
Upgrading the node version to `v14` (`node:14.19-alpine3.15` in my case) in Dockerfile fixed the issue for me.

**Comment by uvinod** [comment]
node: v16.15.0
Redis server v=6.0.16
redis: "^4.1.0"

I have the same issue. Can someone assist me with the fix?

**Comment by Luxiorawa** [comment]
The "issue" may be fixed by changing package.json. In my case, i had the following dependency "redis": "^4.0.6".

The "^" sign means that it can upgrade patch version, or minor version. 4.1.0 is a minor version, so i couldn't launch my app because my node version is 12.15.0 (thus, not including optional chaining)

In case you want one specific version, you can specify so in the package.json by specifying "redis": "4.0.6" (without "^").

**Comment by well1791** [comment]
Isn't there a way to require a minimum node version so that it's visible to everyone facing this issue?

```js
/// package.json
"engines" : { 
  "npm" : ">=14",
}
```

or something like [this](https://github.com/facebook/react/blob/main/package.json#L102-L104)

In any case, these

https://github.com/redis/node-redis/blob/01edb7c3057460a384892d89abf15ee12c9592a4/package.json#L34

https://github.com/redis/node-redis/blob/01edb7c3057460a384892d89abf15ee12c9592a4/tsconfig.base.json#L2

are the only lines that provide visibility

**Comment by stockarea** [comment]
I am getting this on node version 20 as well.

**Comment by shobhithh** [comment]
Hi @stockarea,
Did you find any work around for this, even i am using the node version of 22 and getting the same error.
