### ISSUE TITLE
Unexpected token . - ...options?.modules

### ISSUE THREAD

**Issue by devasishg** [redis/node-redis#2131]
**Environment:**
 - **Node.js Version**: v11.2.0
 - **Redis Server Version**: 5.0.3
 - **Node Redis Version**: 4.0.6
 - **Platform**: node:11.2.0-alpine + any docker image

usr/src/app/node_modules/redis/dist/index.js:42
            ...options?.modules
                       ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:760:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/usr/src/app/config/redis_connector.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
root@ee0301c9b03e:/usr/src/app# node --version

**Comment by leibale** [comment]
Duplicate of https://github.com/redis/node-redis/issues/2117

**Comment by guptaarpit** [comment]
Still facing same issue for docker node:14-alpine, Can someone help what need to be on Docker

**Comment by bhartendu27** [comment]
Upgrading my node version to current stable version fixed it for me. (my strapi version: 3.6.8)

```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```

**Comment by depyronick** [comment]
updated node and npm also cached cleans etc, still the same.

**Comment by nguemechieu** [comment]
I had the same issue and run
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
This worked for me .Thanks

**Comment by ashioyajotham** [comment]
Thank you very much @bhartendu27 @nguemechieu :)
