### ISSUE TITLE
TypeError: command.transformArguments is not a function when executing zRange command

### ISSUE THREAD

**Issue by TheNaman047** [redis/node-redis#2221]
I am trying to execute `zRange` command as follows
```
try {
  const res = await client.zRange("test", 0, -1, {
    REV: true,
  });
  console.log("res: ", res);
} catch (error) {
  console.log("tes2: ", error);
}
```

Look for the `REV: true` here. When I execute the above command with 'REV' argument, am getting following error. 

Note: It is working well on Ubuntu 20 and 22 with same version of node-redis, node and redis-server. Not sure why this is only occurring in Windows.

 2022-08-04T09:35:50.180Z  { FIRST_KEY_INDEX: 1, IS_READ_ONLY: true, transformArguments: '' } [ 'test', 0, -1 ] zRange
 2022-08-04T09:35:50.186Z  tes2:  TypeError: command.transformArguments is not a function
    at transformCommandArguments (E:\zoga-backend\node_modules\@redis\client\dist\lib\commander.js:72:23)
    at Commander.commandsExecutor (E:\zoga-backend\node_modules\@redis\client\dist\lib\client\index.js:169:88)
    at Commander.BaseClass.<computed> [as zRange] (E:\zoga-backend\node_modules\@redis\client\dist\lib\commander.js:9:29)
    at Commander.<anonymous> (E:\zoga-backend\database\redis\index.js:42:32)
    at Commander.emit (node:events:527:28)
    at Commander.emit (node:domain:475:12)
    at RedisSocket.<anonymous> (E:\zoga-backend\node_modules\@redis\client\dist\lib\client\index.js:352:35)
    at RedisSocket.emit (node:events:527:28)
    at RedisSocket.emit (node:domain:475:12)
    at RedisSocket._RedisSocket_connect (E:\zoga-backend\node_modules\@redis\client\dist\lib\client\socket.js:114:14)

```

![image](https://user-images.githubusercontent.com/25585634/182815815-c3db5347-f1b0-451e-9371-277b93d9210e.png)

**Environment:**
 - **Node.js Version**: 16.15.0
 - **Redis Server Version**: 5.0.7 and 7.0.4
 - **Node Redis Version**: 4.2.0
 - **Platform**: Windows 11

**Comment by TheNaman047** [comment]
Not sure what was the exact reason out of the following two, but they somehow fixed the above issue.

1. Shifted terminal from 'powershell' to 'git bash'
2. Removed, `node_modules`
3. Did `npm i`
4. Ran it again and issue was gone :)
