### ISSUE TITLE
Getting TypeError: Invalid argument type, When valuetype is object in HSET

### ISSUE THREAD

**Issue by praveenydv** [redis/node-redis#2224]
I found some issue with hSet function:

1). I am trying to set values to multiple hash fields using hSet:
```  
  await client.hSet('key', { field: 'value',field2: 'value2' });
```
But I am getting Invalid argument type error :
```
(node:219801) UnhandledPromiseRejectionWarning: TypeError: Invalid argument type
    at encodeCommand (/home/lenovo/Desktop/kubernetes_General_pods/servicetest/node_modules/@redis/client/dist/lib/client/RESP2/encoder.js:17:19)
    at RedisCommandsQueue.getCommandToSend (/home/lenovo/Desktop/kubernetes_General_pods/servicetest/node_modules/@redis/client/dist/lib/client/commands-queue.js:187:45)
    at Commander._RedisClient_tick (/home/lenovo/Desktop/kubernetes_General_pods/servicetest/node_modules/@redis/client/dist/lib/client/index.js:434:76)
    at Commander._RedisClient_sendCommand (/home/lenovo/Desktop/kubernetes_General_pods/servicetest/node_modules/@redis/client/dist/lib/client/index.js:418:82)
    at Commander.sendCommand (/home/lenovo/Desktop/kubernetes_General_pods/servicetest/node_modules/@redis/client/dist/lib/client/index.js:369:93)
    at Commander.<computed> (/home/lenovo/Desktop/kubernetes_General_pods/servicetest/node_modules/@redis/client/dist/lib/client/index.js:406:27)
    ```
2). Also, I am handling the promise error in catch but  I am getting "UnhandledPromiseRejectionWarning"  issue. 
3). await is not working for "hSet" function.

**Environment:**
 - **Node.js Version**:14.17.3
 - **Redis Server Version**: 7.0.0
 - **Node Redis Version**: 4.2.0
 - **Platform**: Ubuntu 20.04.3

**Comment by praveenydv** [comment]
this is resolved--
I was using 
```          
  legacyMode: true
```
in connection option. that's why I was getting this error. after changing            
```
 legacyMode: false,
```
everything is fine.
