### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'SETEX')

### ISSUE THREAD

**Issue by asmdhabibullah** [redis/node-redis#2262]
**Environment:**
 - **Node.js Version**: 16.x
 - **Redis Server Version**: 
 - **Node Redis Version**: 4.0.2
 -  - **Platform**:  Heroku Cloud OS

**Comment by leibale** [comment]
Can you share some code?

**Comment by asmdhabibullah** [comment]
Sure, please have a look

export const REDIS_URI = NODE_ENV ? process.env.REDIS_DEV_URL : `redis://default:${process.env.REDIS_PASS}@${process.env.REDIS_URL}`;

import { createClient } from 'redis';
import { REDIS_URI } from '../config';

export let redisClient;

// Dev & Prod
(async () => {
    try {
        redisClient = createClient({ url: REDIS_URI });
        // redisClient.on("connect", () => { 
        // })
        redisClient.on("error", (err) => console.log("Redis Client Connection Error"));

        console.log("Redis cashe app database connected...");
        await redisClient.connect();
        // if (NODE_ENV) {
        // } else {
        //     redisClient = createClient({
        //         url: REDIS_URI});
        //     redisClient.on("error", (err) => console.log("Redis Client Connection Error", err));

        //     console.log("Redis cashe app database connected...");
        //     await redisClient.connect();
        // }
    } catch (error) {
        console.log('Redis app connection Error...', error);
    }
})();

// import { createClient } from 'redis';
// import { NODE_ENV, REDIS_PASS, REDIS_URI } from '../config';

// export let redisClient

// // Dev & Prod
// (async () => {
//     try {
//         if (NODE_ENV) {
//             redisClient = createClient({
//                 url: REDIS_URI,
//                 socket: {
//                     rejectUnauthorized: false
//                 },
//             });
//             // redisClient.on("connect", () => { 
//             // })
//             redisClient.on("error", (err) => console.log("Redis Client Connection Error", err));

//             console.log("Redis cashe app database connected...");
//             await redisClient.connect();
//         } else {
//             redisClient = createClient({
//                 url: REDIS_URI,
//                 password: REDIS_PASS,
//                 socket: {
//                     tls: false,
//                     rejectUnauthorized: false
//                 },
//             });
//             redisClient.on("error", (err) => console.log("Redis Client Connection Error", err));

//             console.log("Redis cashe app database connected...");
//             await redisClient.connect();
//         }
//     } catch (error) {
//         console.log('Redis app connection Error...', error);
//     }
// })();

**Comment by leibale** [comment]
Can you please share the stack trace of the error ("TypeError: Cannot read properties of undefined (reading 'SETEX')")?

**Comment by asmdhabibullah** [comment]
Node.js Version: 16.x
Redis Server Version: 
Node Redis Version: 4.0.2
Platform: Heroku Cloud OS

**Comment by leibale** [comment]
@asmdhabibullah by "stack trace" I mean the extra info after the error message it self:

```
Error
    **at test (<anonymous>:2:11)**
    **at <anonymous>:1:1**
```

**Comment by asmdhabibullah** [comment]
2022-09-14T14:59:46.099027+00:00 app[web.1]: /app/dist/controller/contact/index.js:212
2022-09-14T14:59:46.099044+00:00 app[web.1]:                         return _redisClient.redisClient.SETEX(key, _config.REDIS_DEF_EXP_TIME, JSON.stringify(contacts));
2022-09-14T14:59:46.099045+00:00 app[web.1]:                                                         ^
2022-09-14T14:59:46.099045+00:00 app[web.1]: 
2022-09-14T14:59:46.099046+00:00 app[web.1]: TypeError: Cannot read properties of undefined (reading 'SETEX')
2022-09-14T14:59:46.099046+00:00 app[web.1]:     at _callee5$ (/app/dist/controller/contact/index.js:212:57)
2022-09-14T14:59:46.099046+00:00 app[web.1]:     at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:63:40)
2022-09-14T14:59:46.099047+00:00 app[web.1]:     at Generator.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:294:22)
2022-09-14T14:59:46.099047+00:00 app[web.1]:     at Generator.next (/app/node_modules/regenerator-runtime/runtime.js:119:21)
2022-09-14T14:59:46.099048+00:00 app[web.1]:     at asyncGeneratorStep (/app/dist/controller/contact/index.js:22:103)
2022-09-14T14:59:46.099048+00:00 app[web.1]:     at _next (/app/dist/controller/contact/index.js:24:194)
2022-09-14T14:59:46.099048+00:00 app[web.1]:     at /app/dist/controller/contact/index.js:24:364
2022-09-14T14:59:46.099048+00:00 app[web.1]:     at new Promise (<anonymous>)
2022-09-14T14:59:46.099049+00:00 app[web.1]:     at /app/dist/controller/contact/index.js:24:97
2022-09-14T14:59:46.099049+00:00 app[web.1]:     at /app/dist/controller/contact/index.js:226:30
2022-09-14T14:59:46.099049+00:00 app[web.1]:     at /app/node_modules/mongoose/lib/model.js:5074:18
2022-09-14T14:59:46.099050+00:00 app[web.1]:     at processTicksAndRejections (node:internal/process/task_queues:78:11)
 -->

**Comment by leibale** [comment]
Are you trying to use it on the client?
