### ISSUE TITLE
Not able to subscribe after publishing message either from cmd or from .publish()

### ISSUE THREAD

**Issue by omkarrepal** [redis/node-redis#2327]
I'm trying to implement pub/sub mechanism but I'm getting error whenever I publish message either from command line or through node package.

My client creation code looks like 

```
async setRedisClient(): Promise<void> {
    let redisOpts: RedisClientOptions = this.cloudConfig.getRedisCredentials();
    this.pubClient = createClient(redisOpts);
    await this.pubClient.connect();
    this.subClient = this.pubClient.duplicate();
    await this.subClient.connect();
  }
getPubClient() {
    return this.pubClient;
  }

  getSubClient() {
    return this.subClient;
  }
  
```

my redis config
```
return {
      socket: {
        host: "localhost"
        port: 6379,
        tls: false
      },
      legacyMode: true,
      password: "1234"
    }
```

And my subscription code looks like:
```
async listenRemoteSockets() {
    logger.info("Subscriber to remote socket updates");
    try {
      // doing this to capture message after 10 seconds.
      setTimeout(async () => {
        await this.redisManager.getPubClient().publish('monitor', 'test from app 22');
      }, 10000);
      await this.redisManager.getSubClient().subscribe('monitor', (err, count) => {
        if (err) {
          logger.error(`>>>>>>>>>>>>> Error occured ${err}`);
        }
        logger.info(`>>>>>>>>>>>>>> Subscribed to ${count}`)
      });

      this.redisManager.getSubClient().on('message', (channel, message) => {
        logger.info(`>>>>>>>>>>>>> Got message from ${channel} => ${message}`)
      })

    } catch (error) {
      logger.error(`Error occured >>>>>>>>>>>>>>> ${error}`)
    }
  }
```

Following error is thrown once I publish from either command or through .publish()

```
Error: Got an unexpected reply from Redis
    at Object.onReply (app.js:2:2830344)
    at exports.default.write (app.js:2:2823283)
    at RedisCommandsQueue.onReplyChunk (app.js:2:2835206)
    at RedisSocket.<anonymous> (app.js:2:2870390)
    at RedisSocket.emit (node:events:527:28)
    at Socket.<anonymous> (app.js:2:2889095)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
```

**Environment:**
 - **Node.js Version**: v18.3.0
 - **Redis Server Version**: Redis server v=7.0.5 sha=00000000:0 malloc=libc bits=64 build=bc49a85e754011b0
 - **Node Redis Version**: redis@4.3.1
 - **Platform**: Mac OS 12.6.1

**Comment by leibale** [comment]
@omkarrepal 
```javascript
import { createClient } from '@redis/client';

const pub = createClient(),
  sub = pub.duplicate();

await Promise.all([
  pub.connect(),
  sub.connect()
]);

await sub.subscribe('monitor', (channel, message) => {
  console.log(channel, message);
});

setInterval(async () => {
  await pub.publish('monitor', Math.random().toString());
}, 2000);
```

This code did not reproduce the error...

**Comment by omkarrepal** [comment]
Hi @leibale ,

Thanks for quick response. :)

I tried following in client creation code.

Now my code looks like
```
import { createClient } from "@redis/client";
import { RedisClientOptions } from "redis";
import { CloudConfig } from "../cloud-config";

export class RedisManager {
  private pubClient: ReturnType<typeof createClient>;
  private subClient: ReturnType<typeof createClient>;
  constructor(private cloudConfig: CloudConfig) {
  }

  async setRedisClient(): Promise<void> {
    let redisOpts: RedisClientOptions = this.cloudConfig.getRedisCredentials();
    this.pubClient = createClient(redisOpts);
    this.subClient = this.pubClient.duplicate();
    await Promise.all([
      this.pubClient.connect(),
      this.subClient.connect()
    ]);
    await this.subClient.subscribe('monitor', (channel, message) => {
      console.log(channel, message);
    });
  }

  getPubClient() {
    return this.pubClient;
  }

  getSubClient() {
    return this.subClient;
  }
}
```

it prints following from console.log

`null [ 'subscribe', 'monitor', 1 ]`

Then I ran following command from `redis-cli`
`127.0.0.1:6379> PUBLISH monitor test`

and it again thrown following error.

```
Error: Got an unexpected reply from Redis
    at Object.onReply (/Users///terminal-ui/dist/app.js:2:2805176)
    at exports.default.write (/Users///terminal-ui/dist/app.js:2:2798115)
    at RedisCommandsQueue.onReplyChunk (/Users///terminal-ui/dist/app.js:2:2810038)
    at RedisSocket.<anonymous> (/Users///terminal-ui/dist/app.js:2:2845464)
    at RedisSocket.emit (node:events:527:28)
    at Socket.<anonymous> (/Users///terminal-ui/dist/app.js:2:2864893)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
```

Am I missing something. I've upgraded to redis@latest (4.5.0)

**Comment by leibale** [comment]
Looks like PubSub is not working well with `legacyMode` on, I'll debug it later today

**Comment by omkarrepal** [comment]
@leibale  So the workaround would be turning off a legacy mode.

**Comment by ABHIJITBURMAN** [comment]
I face the same issue, while legacy mode true , i am not able to subscribe any channel in redis, 
using redis(npm) 4.6.6

**Comment by leibale** [comment]
@ABHIJITBURMAN just turn off legacy mode on the subscriber client
