### ISSUE TITLE
Redis get calls intermittently hangs after reconnection

### ISSUE THREAD

**Issue by Karthikeyan-Amaresan** [redis/node-redis#2410]
### Description

In Nodejs Application in Google App Engine, sometimes when redis connection is getting closed and reconnected automatically, few mins after the reconnection, redis get calls in some of the requests hangs without returning the value. Because of that the requests are getting timed-out after 2 Mins (GAE Nodejs Frontend instance request processing Time limit) 

The reconnection before the get calls hangs, everytime happens when making a get call for a key of below format
Expire-LS-12345:UUID

Subsequently after the reconnection, some of the get calls hangs without returning any value in turn causing timeouts. 

### Node.js Version

nodejs10

### Redis Server Version

3.2.13

### Node Redis Version

redis@3.1.2

### Platform

Linux

### Logs

```bash
{ Error: Redis connection to x.x.x.x:6379 failed - write ECONNRESET
    at afterWriteDispatched (internal/stream_base_commons.js:78:25)
    at writeGeneric (internal/stream_base_commons.js:73:3)
    at Socket._writeGeneric (net.js:714:5)
    at Socket._write (net.js:726:8)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Socket.Writable.write (_stream_writable.js:299:11)
    at RedisClient.write (/workspace/node_modules/redis/index.js:950:43)
    at RedisClient.internal_send_command (/workspace/node_modules/redis/index.js:886:14)
    at RedisClient.internal_send_command_trace [as internal_send_command] (/workspace/node_modules/@google-cloud/trace-agent/build/src/plugins/plugin-redis.js:91:50)
    at RedisClient.get (/workspace/node_modules/redis/lib/commands.js:46:25)
    at Promise (internal/util.js:274:30)
    at new Promise (<anonymous>)
    at RedisClient.get (internal/util.js:273:12)
    at ConversationQueueServices.startTimeoutToClearQueueForVisitor (/workspace/ls/Services/ConversationQueueServices.js:306:57)
    at PeoplesService.onVisitorSubscriberLeft (/workspace/ls/Services/PeoplesService.js:278:33)
    at Object.app.post [as handler] (/workspace/app.js:170:27)
    at Object.e [as getRoute] (/workspace/rest-simplified.js:24:9851)
    at IncomingMessage.r.on (/workspace/rest-simplified.js:24:10881)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1145:12) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'write' }
```

**Comment by chayim** [comment]
@Karthikeyan-Amaresan There have been significant improvements and changes made along the way, especially to the connection. Can you try the latest 4.6.x?

**Comment by Karthikeyan-Amaresan** [comment]
Okay @chayim . So upgrading nodejs client to 4.6.x also means the need for upgrading the redis server version to 5.0 or Above. isn't it? Because latest nodejs client 4.6.x only supports redis 5.0 or above as per the official documentation.

**Comment by Karthikeyan-Amaresan** [comment]
Thank you @chayim for the suggestion. We will update the redis client to the specified version and check again.
