### ISSUE TITLE
V4.6.5: Create Client import statement throws error 

### ISSUE THREAD

**Issue by rvc-dev-react** [redis/node-redis#2435]
### Description

The createClient func in the lib seems to be broken? Vue 3 Application / Vite 
   
```
import { createClient } from 'redis';

class RedisService {
    constructor() {
        this.client = createClient();
        this.client.on('error', err => console.log('Redis Client Error', err));
    }

    async connect() {
        await this.client.connect();
        console.info('Redis Client Connected', this.client);
    }

    async disconnect() {
        await this.client.disconnect();
    }
}

const redisService = new RedisService()
export { redisService } 
```
  

### Node.js Version

v19.3.0

### Redis Server Version

6.2.10

### Node Redis Version

4.6.5

### Platform

macOS

### Logs

```bash
socket.js:20 Uncaught TypeError: Class extends value undefined is not a constructor or null
    at node_modules/@redis/client/dist/lib/client/socket.js (socket.js:20:36)
    at __require (chunk-RSJERJUL.js?v=f3ccfd1b:3:50)
    at node_modules/@redis/client/dist/lib/client/index.js (index.js:16:18)
    at __require (chunk-RSJERJUL.js?v=f3ccfd1b:3:50)
    at node_modules/@redis/client/dist/index.js (index.js:18:18)
    at __require (chunk-RSJERJUL.js?v=f3ccfd1b:3:50)
    at node_modules/redis/dist/index.js (index.js:18:18)
    at __require (chunk-RSJERJUL.js?v=f3ccfd1b:3:50)
    at index.js:56:25
```

**Comment by rvc-dev-react** [comment]
My code breaks just by importing { createClient } from redis

**Comment by rvc-dev-react** [comment]
> This package only works in node, not in the browser..

Fair enough, I wanted to make a dev tool to quickly query data from redis, I guess I'll have to stand up a middleman server
