### ISSUE TITLE
Exception thrown when adding number to a stream

### ISSUE THREAD

**Issue by jsilvao** [redis/node-redis#2449]
### Description

This:
```
await redisClient.sendCommand(['XADD', 'someStream', '*', 'value', numberVariable])
```
Throws
```
TypeError('Invalid argument type');
```

But this works: 
```
await redisClient.sendCommand(['XADD', 'someStream', '*', 'value', 'someString'])
```

### Node.js Version

v18.12.1

### Redis Server Version

6.2.11

### Node Redis Version

4.6.5

### Platform

Ubuntu 22.04 Server

### Logs

```bash
/opt/services/sftp-processor/node_modules/@redis/client/dist/lib/client/RESP2/encoder.js:17
            throw new TypeError('Invalid argument type');
                  ^

TypeError: Invalid argument type
    at encodeCommand (/opt/services/sftp-processor/node_modules/@redis/client/dist/lib/client/RESP2/encoder.js:17:19)
    at RedisCommandsQueue.getCommandToSend (/opt/services/sftp-processor/node_modules/@redis/client/dist/lib/client/commands-queue.js:138:45)
    at Commander._RedisClient_tick (/opt/services/sftp-processor/node_modules/@redis/client/dist/lib/client/index.js:507:76)
    at Commander._RedisClient_sendCommand (/opt/services/sftp-processor/node_modules/@redis/client/dist/lib/client/index.js:494:82)
    at Commander.sendCommand (/opt/services/sftp-processor/node_modules/@redis/client/dist/lib/client/index.js:196:100)
    at FSWatcher.<anonymous> (/opt/services/sftp-processor/index.js:161:20)
```

**Comment by leibale** [comment]
That's the expected behavior, Redis arguments must be of type `string | Buffer`.
