### ISSUE TITLE
Property 'createClient' does not exist on @types/redis-mock/index with Mocha unit testing

### ISSUE THREAD

**Issue by NikolayChankov90** [redis/node-redis#2523]
### Description

`import * as RedisMock from 'redis-mock';`

```
describe('RedisAdoption', () => {
 let redisClient: any; // Mock Redis client
   it('should create a redis adoption  instance', async () => {
        redisAdoption'= new RedisAdoption('localhost', 6379);
    });

    it('should create a redis mock client', async () => {
        redisClient = RedisMock.createClient(); // here it fails
        
        // tried with RedisMock.createClient( {host: '127.0.0.1', port: 6379} ) , but fails again

        redisAdapter.redis = redisClient;
    });
}
```

ERROR: 

```
Property 'createClient' does not exist on type 'typeof import("C:/Redis/redis-service/node_modules/@types/redis-mock/index")'.
  redisClient = RedisMock.createClient();
```

### Node.js Version

18.13.0

### Redis Server Version

6.0.16

### Node Redis Version

4.6.6

### Platform

Windows

### Logs

```bash
TSError: ⨯ Unable to compile TypeScript:
test/redis/redis.functionality.spec.ts:15:33 - error TS2339: Property 'createClient' does not exist on type 'typeof import("C:/redis/redis-service/node_modules/@types/redis-mock/index")'.

15         redisClient = RedisMock.createClient();
                                   ~~~~~~~~~~~~

    at createTSError (C:\redis\redis-service\node_modules\ts-node\src\index.ts:859:12)
    at reportTSError (C:\redis\redis-service\node_modules\ts-node\src\index.ts:863:19)
    at getOutput (C:\redis\redis-service\node_modules\ts-node\src\index.ts:1077:36)
    at Object.compile (C:\redis\redis-service\node_modules\ts-node\src\index.ts:1433:41)
    at Module.m._compile (C:\redis\redis-service\node_modules\ts-node\src\index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .ts] (C:\redis\redis-service\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.exports.requireOrImport (C:\redis\redis-service\node_modules\mocha\lib\nodejs\esm-utils.js:53:16)
    at async Object.exports.loadFilesAsync (C:\redis\redis-service\node_modules\mocha\lib\nodejs\esm-utils.js:100:20)
    at async singleRun (C:\redis\redis-service\node_modules\mocha\lib\cli\run-helpers.js:125:3)
    at async Object.exports.handler (C:\redis\redis-service\node_modules\mocha\lib\cli\run.js:370:5)
```

**Comment by avinashkrishna613** [comment]
Did you try `import RedisMock from "redis-mock"` instead?

**Comment by uglide** [comment]
Hi @avinashkrishna613 
Please see my comment here https://github.com/redis/node-redis/issues/2546#issuecomment-1613022232
If you think we should support both Jest and Mocha, comment so other users can upvote it. Thanks!

**Comment by NikolayChankov90** [comment]
I think you should support both , yes . :)
