### ISSUE TITLE
How to use (or mock) redis in jest tests

### ISSUE THREAD

**Issue by blagae** [redis/node-redis#2546]
### Description

I am struggling to find a way to combine the modern Redis v4 client with the jest test framework.

This is my production code:

```
import redis from 'redis';
import config from './config';
import logger from './logger';

const redisClient = redis.createClient(config.redisConfig);
redisClient.on('error', (e) => logger.error(e));

(async () => {
  await redisClient.connect();
})();

export type RedisClient = typeof redisClient;
export default async () => {
  const clone = redisClient.duplicate();
  await clone.connect();
  return clone;
};
```

Some of my services of course use redis, and when I try to test them, the entire test suite usually fails at startup. This is a project that was migrated from plain JS to TS, from node-redis 3 to 4, and from mocha to jest.

Below are a few scenarios that don't work.

## No config added:

```
FAIL lib/services/tests/area.spec.ts
  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'createClient')

      4 |
    > 5 | const redisClient = redis.createClient(config.redisConfig);
        |                           ^

      at Object.createClient (lib/redis-client.ts:5:27)
```

### in package.json

```
  "jest": {
    "setupFilesAfterEnv": [
      "./jest.setup.redis-mock.js"
    ]
  },
```

### in jest.setup.redis-mock.js

```
import {jest} from '@jest/globals';
jest.mock('redis', () => jest.requireActual('redis-mock'));
```

Gives the error:

```
FAIL lib/services/tests/area.spec.ts
    TypeError: redisClient.connect is not a function

       8 | (async () => {
    >  9 |   await redisClient.connect();
         |                     ^
      10 | })();

      at connect (lib/redis-client.ts:9:21)
      at asyncGeneratorStep (lib/redis-client.ts:3:31)
```

Messing around in the jest setup file usually ends up with the entire library being undefined, etc.

**Comment by berthoogsteyns** [comment]
i have the same issue

**Comment by uglide** [comment]
Hi @blagae 
Thanks for reporting this issue. Redis-mock package is outdated and doesn't work properly with Node-Redis v4.
We plan to provide an official mocking library for Node-redis v5. I'll post an update here once we have a preview release to test. 

Please stay tuned.

**Comment by blagae** [comment]
Hi @uglide 

Thanks for your reply. If you're still accepting and/or starting feature requests such as this for the new version, it looks like the release of v5 is not for the very near future. Is there a way that I can follow the current goals, the progress towards it, and/or some milestones ? I haven't found a comprehensive overview.

Alternatively, do you know why the node-redis library doesn't allow being used in a jest test run ? Is it something with an env variable or another type of global flag ? I wouldn't mind messing around with it a bit, including actually running a Redis server to test my code.

**Comment by EvanSanderson** [comment]
Any updates on this? Having similar issues with migrating to node redis v4 - a big portion of our existing tests that rely on `redis-mock` fail. It would be great to get something from within the library itself, or any guidance on how to best mock the client in the new rendition of the library. Thanks!

**Comment by adamperez** [comment]
Bumping this; I am now running into the same issue with `redis-mock` (or any other mocking libraries) with redis `v4`.

**Comment by cefeboru** [comment]
It's the same situation for me 🙃 - Trying to upgrade to redis v4 but I am having issues with our tests

**Comment by ibukunoluwayomi** [comment]
bumping this up! It's such a pain 😇

**Comment by matthewwasbrough-cognitant** [comment]
For anyone else coming across this, it isn't a pretty fix but it is a work around until there is a proper mock as mentioned is coming in v5. 

in my `jest.config.js` I have

```
module.exports = {
  ...,
  setupFilesAfterEnv: ['./jest.setup.redis-mock.js', 'jest-extended/all'],
}
```

Then in the `jest.setup.redis-mock.js` file I have 

```
jest.mock('redis', () => ({
  createClient: jest.fn().mockReturnValue({
    on: jest.fn(),
    connect: jest.fn(),
    get: jest.fn(),
    set: jest.fn(),
    expire: jest.fn(),
  }),
}));
```

I'm actually not using `redis-mock` in the end. Where I need explicit return values from the `get`, `set`, or `expire` I mock the wrapping functions to return a specific value. The functions here just work to catch any additional un-mocked usages.

**Comment by the-nishant-singh** [comment]
I am trying to set up tests. Node-Redis v5 is out, so do we have any mocking libraries for v5?

**Comment by Coinhexa** [comment]
Not only jest but also vitest compatible

**Comment by criskell** [comment]
Any updates on this, please?

**Comment by fatal10110** [comment]
For the v5/Jest/Vitest use case discussed here, another option is to keep the real `redis` client and point it at an in-memory **Redis-compatible server implemented in JavaScript/TypeScript**. This avoids substituting a client implementation that lacks `connect()` or `duplicate()`.

I maintain [js-redis-server](https://github.com/fatal10110/js-redis-server). The server itself runs in JavaScript: it does not download or launch a Redis binary, and it needs no Docker container. Lua scripting uses WebAssembly. Its `createRedisMock()` starts the server on a random local port; it is a third-party test double, not the official mocking library requested here.

```js
import { createClient } from 'redis';
import { createRedisMock } from 'js-redis-server';

const mock = await createRedisMock();
const client = createClient({ url: mock.url });
client.on('error', console.error);
try {
  await client.connect();
  await client.set('key', 'value');
  console.log(await client.get('key')); // 'value'
} finally {
  if (client.isOpen) await client.close();
  await mock.close();
}
```

With the import-time connection in the original example, start the mock and supply its URL **before importing the application module**, or inject a connected client. Replacing the package alone won't fix that startup ordering. In Jest/Vitest, the lifecycle can live in async setup/teardown hooks; close any duplicate clients there too.

I checked the published `js-redis-server@0.2.0` with `redis@5.12.1` on Node 22.12.0, including `duplicate().connect()`, shared reads and cleanup. The mock requires Node 22+. This example uses the v5 `close()` API; v4 uses `quit()`. It exercises real local sockets, so use normal timers for client startup. Keep tests against real Redis for production compatibility and features outside the mock's implemented command set.
