### ISSUE TITLE
Broken in node 20

### ISSUE THREAD

**Issue by KernelDeimos** [redis/node-redis#2551]
### Description

It doesn't work until I add `process.EventEmitter = require('events')` to the top of my script.

```
RedisParser.prototype = Object.create(process.EventEmitter.prototype);
                                                           ^

TypeError: Cannot read properties of undefined (reading 'prototype')
    at Object.<anonymous> (/home/edube/myrepo/node_modules/node-redis/parser.js:36:60)
    at Module._compile (node:internal/modules/cjs/loader:1267:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1321:10)
    at Module.load (node:internal/modules/cjs/loader:1125:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at Module.require (node:internal/modules/cjs/loader:1149:19)
    at require (node:internal/modules/helpers:121:18)
    at Object.<anonymous> (/home/edube/myrepo/node_modules/node-redis/index.js:26:14)
    at Module._compile (node:internal/modules/cjs/loader:1267:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1321:10)
```

### Node.js Version

v20.1.0

### Redis Server Version

7.0.11

### Node Redis Version

0.1.7

### Platform

Linux

**Comment by KernelDeimos** [comment]
Oh, the repo is `node-redis` but the package is `redis`. That's not confusing at all.
