### ISSUE TITLE
RedisClient failed to reconnect with specific database number(other than zero) after redis container restarted

### ISSUE THREAD

**Issue by r-sugi** [redis/node-redis#2564]
### Description

Code snippet(with Nest.js case) for connect/reconnect the redis is below.

```
#SampleService.ts

import {
  createClient,
  RedisClientOptions,
} from 'redis';

const redisClientOptions: RedisClientOptions = {
  url: baseUrl,
  database: 2,    // other than 0 based on https://github.com/redis/node-redis/blob/master/docs/client-configuration.md#:~:text=Redis%20database%20number
  legacyMode: true,
};

this.client = createClient(redisClientOptions);

// Redis event listener
this.client.on('connect', () => this.logger.log('Redis connect'));

this.client.on('ready', () => this.logger.log('Redis ready'));

this.client.on('end', () => this.logger.log('Redis end'));

this.client.on('error', (error) => {
  this.logger.error(error);
});

this.client.on('reconnecting', () => this.logger.log('Redis reconnecting'));

this.client.on('sharded-channel-moved', () => this.logger.log('Redis sharded-channel-moved'));
```

log shows wrong status  (redis client number which`redis-cli` then `info clients` shows is also wrong.)
event reconnect -> connect -> (ready is not emitted)
```
[Nest] 88759  - 2023/07/10 9:37:17     LOG - 2023/07/10 18:37:17+09:00 - [NOT_SET_CORRECTION_ID] "Nest application successfully started"
[Nest] 88758  - 2023/07/10 9:37:20   ERROR [SampleService] - 2023/07/10 18:37:20+09:00 - [NOT_SET_CORRECTION_ID] {"stack":"Error: Socket closed unexpectedly\n    at Socket.<anonymous> (/Users/ryo/work/tkg/monorepo/aggregate/node_modules/@redis/client/dist/lib/client/socket.js:195:118)\n    at Object.onceWrapper (node:events:628:26)\n    at Socket.emit (node:events:513:28)\n    at TCP.<anonymous> (node:net:322:12)","object":{}}
[Nest] 88759  - 2023/07/10 9:37:20   ERROR [SampleService] - 2023/07/10 18:37:20+09:00 - [NOT_SET_CORRECTION_ID] {"stack":"Error: Socket closed unexpectedly\n    at Socket.<anonymous> (/Users/ryo/work/tkg/monorepo/aggregate/node_modules/@redis/client/dist/lib/client/socket.js:195:118)\n    at Object.onceWrapper (node:events:628:26)\n    at Socket.emit (node:events:513:28)\n    at TCP.<anonymous> (node:net:322:12)","object":{}}
[Nest] 88759  - 2023/07/10 9:37:20     LOG [SampleService] - 2023/07/10 18:37:20+09:00 - [NOT_SET_CORRECTION_ID] "Redis reconnecting"
[Nest] 88758  - 2023/07/10 9:37:20     LOG [SampleService] - 2023/07/10 18:37:20+09:00 - [NOT_SET_CORRECTION_ID] "Redis reconnecting"
[Nest] 88758  - 2023/07/10 9:37:20     LOG [SampleService] - 2023/07/10 18:37:20+09:00 - [NOT_SET_CORRECTION_ID] "Redis connect"
[Nest] 88759  - 2023/07/10 9:37:20     LOG [SampleService] - 2023/07/10 18:37:20+09:00 - [NOT_SET_CORRECTION_ID] "Redis connect"
```

I set the below part commentout
```
if (this.#selectedDB !== 0) {
    promises.push(
        this.#queue.addCommand(
            ['SELECT', this.#selectedDB.toString()],
            { asap: true }
        )
    );
}
```
https://github.com/redis/node-redis/blob/master/packages/client/lib/client/index.ts#L259..L266

Then log shows correctly (redis client number which`redis-cli` then `info clients` shows is also correct.)
event reconnect -> connect -> ready is emitted!!
```
[Nest] 89359  - 2023/07/10 9:45:40   ERROR [SampleService] - 2023/07/10 18:45:40+09:00 - [NOT_SET_CORRECTION_ID] {"stack":"Error: connect ECONNREFUSED 127.0.0.1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)","object":{"errno":-61,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":6379}}
[Nest] 89360  - 2023/07/10 9:45:40   ERROR [SampleService] - 2023/07/10 18:45:40+09:00 - [NOT_SET_CORRECTION_ID] {"stack":"Error: connect ECONNREFUSED 127.0.0.1:6379\n    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)","object":{"errno":-61,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":6379}}
[Nest] 89360  - 2023/07/10 9:45:41     LOG [SampleService] - 2023/07/10 18:45:41+09:00 - [NOT_SET_CORRECTION_ID] "Redis reconnecting"
[Nest] 89359  - 2023/07/10 9:45:41     LOG [SampleService] - 2023/07/10 18:45:41+09:00 - [NOT_SET_CORRECTION_ID] "Redis reconnecting"
[Nest] 89359  - 2023/07/10 9:45:41     LOG [SampleService] - 2023/07/10 18:45:41+09:00 - [NOT_SET_CORRECTION_ID] "Redis connect"
[Nest] 89360  - 2023/07/10 9:45:41     LOG [SampleService] - 2023/07/10 18:45:41+09:00 - [NOT_SET_CORRECTION_ID] "Redis connect"
[Nest] 89360  - 2023/07/10 9:45:41     LOG [SampleService] - 2023/07/10 18:45:41+09:00 - [NOT_SET_CORRECTION_ID] "Redis ready"
[Nest] 89359  - 2023/07/10 9:45:41     LOG [SampleService] - 2023/07/10 18:45:41+09:00 - [NOT_SET_CORRECTION_ID] "Redis ready"
```

### Node.js Version

18.16.0

### Redis Server Version

6.0.14

### Node Redis Version

4.6.7

### Platform

Linux, docker redis:6.0.14 container

**Comment by leibale** [comment]
Can you please check which version of `@redis/client` are you using (if you are using `npm` you can use `npm ls @redis.client`)? Because I just checked the last two versions on npm (1.5.7, .15.8), and in both of them this line is not commented out (line 365 both [in version 1.5.7](https://www.npmjs.com/package/@redis/client/v/1.5.7?activeTab=code), [and 1.5.8](https://www.npmjs.com/package/@redis/client/v/1.5.8?activeTab=code)...

**Comment by r-sugi** [comment]
@leibale 

> Can you please check which version of `@redis/client` are you using (if you are using `npm` you can use `npm ls @redis.client`)? Because I just checked the last two versions on npm (1.5.7, .15.8), and in both of them this line is not commented out (line 365 both [in version 1.5.7](https://www.npmjs.com/package/@redis/client/v/1.5.7?activeTab=code), [and 1.5.8](https://www.npmjs.com/package/@redis/client/v/1.5.8?activeTab=code)...

I meant that I tried to debug part of `@redis/client` with comment out.
I think this part has something wrong ("ready" event is not emitted) when reconnecting.
