### ISSUE TITLE
SADD cannot add numbers

### ISSUE THREAD

**Issue by hypo-thesis** [redis/node-redis#2591]
### Description

R.sAdd('bot' , 1499504461) results into 

```
TypeError: Invalid argument type
    at encodeCommand (/www/wwwroot/v2.mydomain.com.tr/api/node_modules/@redis/client/dist/lib/client/RESP2/encoder.js:17:19)
    at RedisCommandsQueue.getCommandToSend (/www/wwwroot/v2.mydomain.com.tr/api/node_modules/@redis/client/dist/lib/client/commands-queue.js:138:45)
    at Commander._RedisClient_tick (/www/wwwroot/v2.mydomain.com.tr/api/node_modules/@redis/client/dist/lib/client/index.js:515:76)
    at Commander._RedisClient_sendCommand (/www/wwwroot/v2.mydomain.com.tr/api/node_modules/@redis/client/dist/lib/client/index.js:502:82)
    at Commander.commandsExecutor (/www/wwwroot/v2.mydomain.com.tr/api/node_modules/@redis/client/dist/lib/client/index.js:188:154)
    at BaseClass.<computed> [as sAdd] (/www/wwwroot/v2.mydomain.com.tr/api/node_modules/@redis/client/dist/lib/commander.js:8:29)
    at Object.callback (file:///www/wwwroot/v2.mydomain.com.tr/api/server.js:106:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

while 
R.sAdd('bot' , "1499504461") works fine

### Node.js Version

20.0.3

### Redis Server Version

6.8

### Node Redis Version

7

### Platform

ubuntu 20

**Comment by leibale** [comment]
Redis se members are of type `Bulk String`, which is equivalent to `string | Buffer` in javascript. Make sure to pass in either a `string` or a `Buffer`.
