### ISSUE TITLE
Fail to use mSet command

### ISSUE THREAD

**Issue by tungrix** [redis/node-redis#2684]
### Description

I am trying to use the `MSET` command
```javascript
const redisClient = await createClient({ url: REDIS_ENDPOINT })
  .on("error", (err) => console.log("Redis Client Error", err))
  .connect();

await  redisClient.mSet(["key1", 1, "key2", 2]);
```

### Node.js Version

20.0.0

### Redis Server Version

7.2

### Node Redis Version

4.6.12

### Platform

Linux

### Logs

```bash
node:internal/process/esm_loader:40
       internalBinding('errors').triggerUncaughtException(
                                 ^
 
 TypeError: Invalid argument type
     at encodeCommand (/usr/src/app/node_modules/@redis/client/dist/lib/client/RESP2/encoder.js:17:19)
     at RedisCommandsQueue.getCommandToSend (/usr/src/app/node_modules/@redis/client/dist/lib/client/commands-queue.js:138:45)
     at Commander._RedisClient_tick (/usr/src/app/node_modules/@redis/client/dist/lib/client/index.js:536:76)
     at Commander._RedisClient_sendCommand (/usr/src/app/node_modules/@redis/client/dist/lib/client/index.js:523:82)
     at Commander.commandsExecutor (/usr/src/app/node_modules/@redis/client/dist/lib/client/index.js:190:154)
     at /usr/src/app/node_modules/@opentelemetry/instrumentation-redis-4/build/src/instrumentation.js:293:33
     at AsyncLocalStorage.run (node:async_hooks:346:14)
     at AsyncLocalStorageContextManager.with (/usr/src/app/node_modules/@opentelemetry/context-async-hooks/build/src/AsyncLocalStorageContextManager.js:33:40)
     at ContextAPI.with (/usr/src/app/node_modules/@opentelemetry/api/build/src/api/context.js:60:46)
     at RedisInstrumentation._traceClientCommand (/usr/src/app/node_modules/@opentelemetry/instrumentation-redis-4/build/src/instrumentation.js:292:39)
 
 Node.js v20.9.0
```

**Comment by leibale** [comment]
`MSET` expects an array of strings, this should work:
```javascript
await  redisClient.mSet(['key1', '1', 'key2', '2']);
```

BTW, this works as well:
```javascript
await  redisClient.mSet({
  key1: '1',
  key2: '2'
});
```
