### ISSUE TITLE
redisClient.sAdd() not working by inputting an Array

### ISSUE THREAD

**Issue by tungrix** [redis/node-redis#2691]
### Description

```javascript
import { createClient } from "redis";

const redisClient = await createClient({ url: REDIS_ENDPOINT })
  .on("error", (err) => console.log("Redis Client Error", err))
  .connect();

await redisClient.sAdd(["test", "[1, 2, 3]", "abc", "239"]);
```

### Node.js Version

21

### Redis Server Version

7.2

### Node Redis Version

4.6.12

### Platform

Linux

### Logs

```bash
node:internal/process/esm_loader:34
      internalBinding('errors').triggerUncaughtException(
                                ^

TypeError: Invalid argument type
    at encodeCommand (/usr/src/app/node_modules/@redis/client/dist/lib/client/RESP2/encoder.js:17:19)
    at RedisCommandsQueue.getCommandToSend (/usr/src/app/node_modules/@redis/client/dist/lib/client/commands-queue.js:138:45)
    at Commander._RedisClient_tick (/usr/src/app/node_modules/@redis/client/dist/lib/client/index.js:536:76)
    at Commander._RedisClient_sendCommand (/usr/src/app/node_modules/@redis/client/dist/lib/client/index.js:523:82)
    at Commander.commandsExecutor (/usr/src/app/node_modules/@redis/client/dist/lib/client/index.js:190:154)
    at /usr/src/app/node_modules/@opentelemetry/instrumentation-redis-4/build/src/instrumentation.js:293:33
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at AsyncLocalStorageContextManager.with (/usr/src/app/node_modules/@opentelemetry/context-async-hooks/build/src/AsyncLocalStorageContextManager.js:33:40)
    at ContextAPI.with (/usr/src/app/node_modules/@opentelemetry/api/build/src/api/context.js:60:46)
    at RedisInstrumentation._traceClientCommand (/usr/src/app/node_modules/@opentelemetry/instrumentation-redis-4/build/src/instrumentation.js:292:39)
```

**Comment by leibale** [comment]
You should use (see [here](https://github.com/redis/node-redis/blob/master/packages/client/lib/commands/SADD.ts)):
```javascript
await client.sAdd('key', ['1', '2', '3']);
```
