### ISSUE TITLE
Unable to connect to literal IPv6 addresses via the `url` option

### ISSUE THREAD

**Issue by TimWolla** [redis/node-redis#2734]
### Description

When using the `url` option one cannot connect to IPv6 addresses:

```
let redis = require('redis');
let c = redis.createClient({ url: 'redis://[::1]:6379', socket: { reconnectStrategy: false } });

c.connect();
```

results in:

```
Error: getaddrinfo ENOTFOUND [::1]
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
```

It works fine when passing the IPv6 address within the `hostname`:

```
let redis = require('redis');
let c = redis.createClient({ socket: { reconnectStrategy: false, hostname: '::1', port: 6379 } });

c.connect();
```

------------------------

It worked fine with node-redis 3.x, but no longer works with node-redis 4.x. The issue is that the `parse` function from the `url` module stripped the square brackets, but the global `URL` constructor does not:

```
> require('url').parse('redis://[::1]:6379');
Url {
  protocol: 'redis:',
  slashes: true,
  auth: null,
  host: '[::1]:6379',
  port: '6379',
  hostname: '::1',
  hash: null,
  search: null,
  query: null,
  pathname: '/',
  path: '/',
  href: 'redis://[::1]:6379/'
}
> new URL('redis://[::1]:6379')
URL {
  href: 'redis://[::1]:6379',
  origin: 'null',
  protocol: 'redis:',
  username: '',
  password: '',
  host: '[::1]:6379',
  hostname: '[::1]',
  port: '6379',
  pathname: '',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
```

### Node.js Version

v21.5.0

### Node Redis Version

4.6.13

### Platform

Linux

### Logs

```bash
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: getaddrinfo ENOTFOUND [::1]
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:118:26)
Emitted 'error' event on Commander instance at:
    at RedisSocket.<anonymous> (/pwd/node_modules/@redis/client/dist/lib/client/index.js:412:14)
    at RedisSocket.emit (node:events:519:28)
    at RedisSocket._RedisSocket_shouldReconnect (/pwd/node_modules/@redis/client/dist/lib/client/socket.js:134:14)
    at RedisSocket._RedisSocket_connect (/pwd/node_modules/@redis/client/dist/lib/client/socket.js:162:117)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Commander.connect (/pwd/node_modules/@redis/client/dist/lib/client/index.js:185:9) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: '[::1]'
}
```

**Comment by b90g** [comment]
I am running into this problem via https://github.com/louislam/uptime-kuma

rediss://kuma:redacted@[fdd0:dead:beef:0:cafe:beef:cafe:dead]:6380

doesnt seem to work  openssl command gave me a certificate back from the same endpoint

Was this fixed and i should rais an issue with uptime kuma to get a newer version?
(apperently they use   "version": "4.5.1",)

**Comment by TimWolla** [comment]
@b90g I verified it as unfixed in the latest version: #3175.
